window.POEMS_DATA = [
  // ===== 咏物篇 (15) =====
  { emoji: '🦆', title: '咏鹅', author: '骆宾王', dynasty: '唐', cat: '咏物', bg: 'nature', lines: ['鹅，鹅，鹅', '曲项向天歌', '白毛浮绿水', '红掌拨清波'] },
  { emoji: '🌿', title: '咏柳', author: '贺知章', dynasty: '唐', cat: '咏物', bg: 'spring', lines: ['碧玉妆成一树高', '万条垂下绿丝绦', '不知细叶谁裁出', '二月春风似剪刀'] },
  { emoji: '🐝', title: '蜂', author: '罗隐', dynasty: '唐', cat: '咏物', bg: 'nature', lines: ['不论平地与山尖', '无限风光尽被占', '采得百花成蜜后', '为谁辛苦为谁甜'] },
  { emoji: '🖼️', title: '画', author: '王维', dynasty: '唐', cat: '咏物', bg: 'landscape', lines: ['远看山有色', '近听水无声', '春去花还在', '人来鸟不惊'] },
  { emoji: '🌺', title: '梅花', author: '王安石', dynasty: '宋', cat: '咏物', bg: 'winter', lines: ['墙角数枝梅', '凌寒独自开', '遥知不是雪', '为有暗香来'] },
  { emoji: '🎋', title: '竹石', author: '郑燮', dynasty: '清', cat: '咏物', bg: 'nature', lines: ['咬定青山不放松', '立根原在破岩中', '千磨万击还坚劲', '任尔东西南北风'] },
  { emoji: '🌬️', title: '风', author: '李峤', dynasty: '唐', cat: '咏物', bg: 'nature', lines: ['解落三秋叶', '能开二月花', '过江千尺浪', '入竹万竿斜'] },
  { emoji: '🌼', title: '菊花', author: '元稹', dynasty: '唐', cat: '咏物', bg: 'autumn', lines: ['秋丛绕舍似陶家', '遍绕篱边日渐斜', '不是花中偏爱菊', '此花开尽更无花'] },
  { emoji: '🪨', title: '石灰吟', author: '于谦', dynasty: '明', cat: '咏物', bg: 'philosophy', lines: ['千锤万凿出深山', '烈火焚烧若等闲', '粉骨碎身浑不怕', '要留清白在人间'] },
  { emoji: '💎', title: '墨梅', author: '王冕', dynasty: '元', cat: '咏物', bg: 'winter', lines: ['吾家洗砚池头树', '朵朵花开淡墨痕', '不要人夸好颜色', '只留清气满乾坤'] },
  { emoji: '🪷', title: '小池', author: '杨万里', dynasty: '宋', cat: '咏物', bg: 'summer', lines: ['泉眼无声惜细流', '树阴照水爱晴柔', '小荷才露尖尖角', '早有蜻蜓立上头'] },
  { emoji: '🌲', title: '青松', author: '陈毅', dynasty: '现代', cat: '咏物', bg: 'winter', lines: ['大雪压青松', '青松挺且直', '要知松高洁', '待到雪化时'] },
  { emoji: '☁️', title: '白云泉', author: '白居易', dynasty: '唐', cat: '咏物', bg: 'landscape', lines: ['天平山上白云泉', '云自无心水自闲', '何必奔冲山下去', '更添波浪向人间'] },
  { emoji: '🌊', title: '浪淘沙', author: '刘禹锡', dynasty: '唐', cat: '咏物', bg: 'water', lines: ['九曲黄河万里沙', '浪淘风簸自天涯', '如今直上银河去', '同到牵牛织女家'] },
  { emoji: '🍃', title: '落叶', author: '孔绍安', dynasty: '唐', cat: '咏物', bg: 'autumn', lines: ['早秋惊落叶', '飘零似客心', '翻飞未肯下', '犹言惜故林'] },

  // ===== 山水篇 (15) =====
  { emoji: '⛰️', title: '望庐山瀑布', author: '李白', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['日照香炉生紫烟', '遥看瀑布挂前川', '飞流直下三千尺', '疑是银河落九天'] },
  { emoji: '🏔️', title: '望天门山', author: '李白', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['天门中断楚江开', '碧水东流至此回', '两岸青山相对出', '孤帆一片日边来'] },
  { emoji: '🏞️', title: '早发白帝城', author: '李白', dynasty: '唐', cat: '山水', bg: 'water', lines: ['朝辞白帝彩云间', '千里江陵一日还', '两岸猿声啼不住', '轻舟已过万重山'] },
  { emoji: '🌄', title: '登鹳雀楼', author: '王之涣', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['白日依山尽', '黄河入海流', '欲穷千里目', '更上一层楼'] },
  { emoji: '🏯', title: '黄鹤楼送孟浩然之广陵', author: '李白', dynasty: '唐', cat: '山水', bg: 'water', lines: ['故人西辞黄鹤楼', '烟花三月下扬州', '孤帆远影碧空尽', '唯见长江天际流'] },
  { emoji: '🌅', title: '忆江南', author: '白居易', dynasty: '唐', cat: '山水', bg: 'spring', lines: ['江南好', '风景旧曾谙', '日出江花红胜火', '春来江水绿如蓝'] },
  { emoji: '🏔️', title: '山行', author: '杜牧', dynasty: '唐', cat: '山水', bg: 'autumn', lines: ['远上寒山石径斜', '白云生处有人家', '停车坐爱枫林晚', '霜叶红于二月花'] },
  { emoji: '🌋', title: '题西林壁', author: '苏轼', dynasty: '宋', cat: '山水', bg: 'landscape', lines: ['横看成岭侧成峰', '远近高低各不同', '不识庐山真面目', '只缘身在此山中'] },
  { emoji: '💦', title: '饮湖上初晴后雨', author: '苏轼', dynasty: '宋', cat: '山水', bg: 'water', lines: ['水光潋滟晴方好', '山色空蒙雨亦奇', '欲把西湖比西子', '淡妆浓抹总相宜'] },
  { emoji: '🌊', title: '观沧海', author: '曹操', dynasty: '汉', cat: '山水', bg: 'water', lines: ['东临碣石', '以观沧海', '水何澹澹', '山岛竦峙'] },
  { emoji: '🏜️', title: '凉州词', author: '王之涣', dynasty: '唐', cat: '山水', bg: 'frontier', lines: ['黄河远上白云间', '一片孤城万仞山', '羌笛何须怨杨柳', '春风不度玉门关'] },
  { emoji: '🏞️', title: '鹿柴', author: '王维', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['空山不见人', '但闻人语响', '返景入深林', '复照青苔上'] },
  { emoji: '🏔️', title: '独坐敬亭山', author: '李白', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['众鸟高飞尽', '孤云独去闲', '相看两不厌', '只有敬亭山'] },
  { emoji: '🌉', title: '枫桥夜泊', author: '张继', dynasty: '唐', cat: '山水', bg: 'night', lines: ['月落乌啼霜满天', '江枫渔火对愁眠', '姑苏城外寒山寺', '夜半钟声到客船'] },
  { emoji: '🏝️', title: '鸟鸣涧', author: '王维', dynasty: '唐', cat: '山水', bg: 'night', lines: ['人闲桂花落', '夜静春山空', '月出惊山鸟', '时鸣春涧中'] },

  // ===== 四季篇 (15) =====
  { emoji: '🌸', title: '春晓', author: '孟浩然', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['春眠不觉晓', '处处闻啼鸟', '夜来风雨声', '花落知多少'] },
  { emoji: '🌱', title: '春夜喜雨', author: '杜甫', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['好雨知时节', '当春乃发生', '随风潜入夜', '润物细无声'] },
  { emoji: '🌿', title: '钱塘湖春行', author: '白居易', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['孤山寺北贾亭西', '水面初平云脚低', '几处早莺争暖树', '谁家新燕啄春泥'] },
  { emoji: '🌸', title: '江南春', author: '杜牧', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['千里莺啼绿映红', '水村山郭酒旗风', '南朝四百八十寺', '多少楼台烟雨中'] },
  { emoji: '🌻', title: '夏日绝句', author: '李清照', dynasty: '宋', cat: '四季', bg: 'summer', lines: ['生当作人杰', '死亦为鬼雄', '至今思项羽', '不肯过江东'] },
  { emoji: '☀️', title: '晓出净慈寺送林子方', author: '杨万里', dynasty: '宋', cat: '四季', bg: 'summer', lines: ['毕竟西湖六月中', '风光不与四时同', '接天莲叶无穷碧', '映日荷花别样红'] },
  { emoji: '🌾', title: '悯农·其一', author: '李绅', dynasty: '唐', cat: '四季', bg: 'summer', lines: ['春种一粒粟', '秋收万颗子', '四海无闲田', '农夫犹饿死'] },
  { emoji: '🌾', title: '悯农·其二', author: '李绅', dynasty: '唐', cat: '四季', bg: 'summer', lines: ['锄禾日当午', '汗滴禾下土', '谁知盘中餐', '粒粒皆辛苦'] },
  { emoji: '🍂', title: '秋夕', author: '杜牧', dynasty: '唐', cat: '四季', bg: 'autumn', lines: ['银烛秋光冷画屏', '轻罗小扇扑流萤', '天阶夜色凉如水', '卧看牵牛织女星'] },
  { emoji: '🍁', title: '山居秋暝', author: '王维', dynasty: '唐', cat: '四季', bg: 'autumn', lines: ['空山新雨后', '天气晚来秋', '明月松间照', '清泉石上流'] },
  { emoji: '🌨️', title: '雪梅', author: '卢梅坡', dynasty: '宋', cat: '四季', bg: 'winter', lines: ['梅雪争春未肯降', '骚人阁笔费评章', '梅须逊雪三分白', '雪却输梅一段香'] },
  { emoji: '🌸', title: '大林寺桃花', author: '白居易', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['人间四月芳菲尽', '山寺桃花始盛开', '长恨春归无觅处', '不知转入此中来'] },
  { emoji: '🌿', title: '村居', author: '高鼎', dynasty: '清', cat: '四季', bg: 'spring', lines: ['草长莺飞二月天', '拂堤杨柳醉春烟', '儿童散学归来早', '忙趁东风放纸鸢'] },
  { emoji: '🍂', title: '暮江吟', author: '白居易', dynasty: '唐', cat: '四季', bg: 'autumn', lines: ['一道残阳铺水中', '半江瑟瑟半江红', '可怜九月初三夜', '露似真珠月似弓'] },
  { emoji: '🌺', title: '游园不值', author: '叶绍翁', dynasty: '宋', cat: '四季', bg: 'spring', lines: ['应怜屐齿印苍苔', '小扣柴扉久不开', '春色满园关不住', '一枝红杏出墙来'] },

  // ===== 田园篇 (12) =====
  { emoji: '🏡', title: '过故人庄', author: '孟浩然', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['故人具鸡黍', '邀我至田家', '绿树村边合', '青山郭外斜'] },
  { emoji: '🌾', title: '四时田园杂兴', author: '范成大', dynasty: '宋', cat: '田园', bg: 'pastoral', lines: ['昼出耘田夜绩麻', '村庄儿女各当家', '童孙未解供耕织', '也傍桑阴学种瓜'] },
  { emoji: '🐂', title: '田园乐', author: '王维', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['萋萋春草秋绿', '落落长松夏寒', '牛羊自归村巷', '童稚不识衣冠'] },
  { emoji: '🌻', title: '宿新市徐公店', author: '杨万里', dynasty: '宋', cat: '田园', bg: 'pastoral', lines: ['篱落疏疏一径深', '树头新绿未成阴', '儿童急走追黄蝶', '飞入菜花无处寻'] },
  { emoji: '🐔', title: '归园田居', author: '陶渊明', dynasty: '魏晋', cat: '田园', bg: 'pastoral', lines: ['种豆南山下', '草盛豆苗稀', '晨兴理荒秽', '带月荷锄归'] },
  { emoji: '🐑', title: '牧童', author: '吕岩', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['草铺横野六七里', '笛弄晚风三四声', '归来饱饭黄昏后', '不脱蓑衣卧月明'] },
  { emoji: '🎋', title: '竹里馆', author: '王维', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['独坐幽篁里', '弹琴复长啸', '深林人不知', '明月来相照'] },
  { emoji: '🌿', title: '寻隐者不遇', author: '贾岛', dynasty: '唐', cat: '田园', bg: 'landscape', lines: ['松下问童子', '言师采药去', '只在此山中', '云深不知处'] },
  { emoji: '🌸', title: '桃花源记（节选）', author: '陶渊明', dynasty: '魏晋', cat: '田园', bg: 'pastoral', lines: ['忽逢桃花林', '夹岸数百步', '中无杂树', '芳草鲜美'] },
  { emoji: '🏡', title: '渭川田家', author: '王维', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['斜阳照墟落', '穷巷牛羊归', '野老念牧童', '倚杖候荆扉'] },
  { emoji: '🐟', title: '渔歌子', author: '张志和', dynasty: '唐', cat: '田园', bg: 'water', lines: ['西塞山前白鹭飞', '桃花流水鳜鱼肥', '青箬笠，绿蓑衣', '斜风细雨不须归'] },
  { emoji: '🌾', title: '田上', author: '聂夷中', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['父耕原上田', '子劚山下荒', '六月禾未秀', '官家已修仓'] },

  // ===== 思乡篇 (12) =====
  { emoji: '🌙', title: '静夜思', author: '李白', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['床前明月光', '疑是地上霜', '举头望明月', '低头思故乡'] },
  { emoji: '🏠', title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', cat: '思乡', bg: 'autumn', lines: ['独在异乡为异客', '每逢佳节倍思亲', '遥知兄弟登高处', '遍插茱萸少一人'] },
  { emoji: '🕊️', title: '回乡偶书', author: '贺知章', dynasty: '唐', cat: '思乡', bg: 'spring', lines: ['少小离家老大回', '乡音无改鬓毛衰', '儿童相见不相识', '笑问客从何处来'] },
  { emoji: '🌅', title: '渡汉江', author: '宋之问', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['岭外音书断', '经冬复历春', '近乡情更怯', '不敢问来人'] },
  { emoji: '🌙', title: '月夜忆舍弟', author: '杜甫', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['戍鼓断人行', '边秋一雁声', '露从今夜白', '月是故乡明'] },
  { emoji: '🏔️', title: '杂诗', author: '王维', dynasty: '唐', cat: '思乡', bg: 'winter', lines: ['君自故乡来', '应知故乡事', '来日绮窗前', '寒梅著花未'] },
  { emoji: '💌', title: '逢入京使', author: '岑参', dynasty: '唐', cat: '思乡', bg: 'frontier', lines: ['故园东望路漫漫', '双袖龙钟泪不干', '马上相逢无纸笔', '凭君传语报平安'] },
  { emoji: '🌊', title: '次北固山下', author: '王湾', dynasty: '唐', cat: '思乡', bg: 'water', lines: ['客路青山外', '行舟绿水前', '潮平两岸阔', '风正一帆悬'] },
  { emoji: '🌙', title: '峨眉山月歌', author: '李白', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['峨眉山月半轮秋', '影入平羌江水流', '夜发清溪向三峡', '思君不见下渝州'] },
  { emoji: '🕯️', title: '夜雨寄北', author: '李商隐', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['君问归期未有期', '巴山夜雨涨秋池', '何当共剪西窗烛', '却话巴山夜雨时'] },
  { emoji: '🌉', title: '宿建德江', author: '孟浩然', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['移舟泊烟渚', '日暮客愁新', '野旷天低树', '江清月近人'] },
  { emoji: '🌨️', title: '除夜作', author: '高适', dynasty: '唐', cat: '思乡', bg: 'winter', lines: ['旅馆寒灯独不眠', '客心何事转凄然', '故乡今夜思千里', '霜鬓明朝又一年'] },

  // ===== 友情篇 (12) =====
  { emoji: '🎵', title: '送杜少府之任蜀州', author: '王勃', dynasty: '唐', cat: '友情', bg: 'landscape', lines: ['城阙辅三秦', '风烟望五津', '与君离别意', '同是宦游人'] },
  { emoji: '🌿', title: '送元二使安西', author: '王维', dynasty: '唐', cat: '友情', bg: 'spring', lines: ['渭城朝雨浥轻尘', '客舍青青柳色新', '劝君更尽一杯酒', '西出阳关无故人'] },
  { emoji: '🌸', title: '赠汪伦', author: '李白', dynasty: '唐', cat: '友情', bg: 'water', lines: ['李白乘舟将欲行', '忽闻岸上踏歌声', '桃花潭水深千尺', '不及汪伦送我情'] },
  { emoji: '⛰️', title: '芙蓉楼送辛渐', author: '王昌龄', dynasty: '唐', cat: '友情', bg: 'water', lines: ['寒雨连江夜入吴', '平明送客楚山孤', '洛阳亲友如相问', '一片冰心在玉壶'] },
  { emoji: '🎶', title: '别董大', author: '高适', dynasty: '唐', cat: '友情', bg: 'winter', lines: ['千里黄云白日曛', '北风吹雁雪纷纷', '莫愁前路无知己', '天下谁人不识君'] },
  { emoji: '🎋', title: '山中送别', author: '王维', dynasty: '唐', cat: '友情', bg: 'landscape', lines: ['山中相送罢', '日暮掩柴扉', '春草明年绿', '王孙归不归'] },
  { emoji: '🌉', title: '送友人', author: '李白', dynasty: '唐', cat: '友情', bg: 'landscape', lines: ['青山横北郭', '白水绕东城', '此地一为别', '孤蓬万里征'] },
  { emoji: '🌙', title: '闻王昌龄左迁龙标遥有此寄', author: '李白', dynasty: '唐', cat: '友情', bg: 'spring', lines: ['杨花落尽子规啼', '闻道龙标过五溪', '我寄愁心与明月', '随风直到夜郎西'] },
  { emoji: '🍷', title: '问刘十九', author: '白居易', dynasty: '唐', cat: '友情', bg: 'winter', lines: ['绿蚁新醅酒', '红泥小火炉', '晚来天欲雪', '能饮一杯无'] },
  { emoji: '🌿', title: '赋得古原草送别', author: '白居易', dynasty: '唐', cat: '友情', bg: 'spring', lines: ['离离原上草', '一岁一枯荣', '野火烧不尽', '春风吹又生'] },
  { emoji: '🌅', title: '送灵澈上人', author: '刘长卿', dynasty: '唐', cat: '友情', bg: 'landscape', lines: ['苍苍竹林寺', '杳杳钟声晚', '荷笠带斜阳', '青山独归远'] },
  { emoji: '☘️', title: '送别', author: '王之涣', dynasty: '唐', cat: '友情', bg: 'spring', lines: ['杨柳东风树', '青青夹御河', '近来攀折苦', '应为别离多'] },

  // ===== 边塞篇 (8) =====
  { emoji: '⚔️', title: '出塞', author: '王昌龄', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['秦时明月汉时关', '万里长征人未还', '但使龙城飞将在', '不教胡马度阴山'] },
  { emoji: '🏹', title: '塞下曲', author: '卢纶', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['月黑雁飞高', '单于夜遁逃', '欲将轻骑逐', '大雪满弓刀'] },
  { emoji: '🐎', title: '凉州词', author: '王翰', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['葡萄美酒夜光杯', '欲饮琵琶马上催', '醉卧沙场君莫笑', '古来征战几人回'] },
  { emoji: '🏔️', title: '从军行', author: '王昌龄', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['青海长云暗雪山', '孤城遥望玉门关', '黄沙百战穿金甲', '不破楼兰终不还'] },
  { emoji: '🏇', title: '马诗', author: '李贺', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['大漠沙如雪', '燕山月似钩', '何当金络脑', '快走踏清秋'] },
  { emoji: '🌙', title: '关山月', author: '李白', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['明月出天山', '苍茫云海间', '长风几万里', '吹度玉门关'] },
  { emoji: '🏹', title: '塞上听吹笛', author: '高适', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['雪净胡天牧马还', '月明羌笛戍楼间', '借问梅花何处落', '风吹一夜满关山'] },
  { emoji: '⚔️', title: '己亥岁', author: '曹松', dynasty: '唐', cat: '边塞', bg: 'frontier', lines: ['泽国江山入战图', '生民何计乐樵苏', '凭君莫话封侯事', '一将功成万骨枯'] },

  // ===== 哲理篇 (8) =====
  { emoji: '💡', title: '游山西村', author: '陆游', dynasty: '宋', cat: '哲理', bg: 'pastoral', lines: ['莫笑农家腊酒浑', '丰年留客足鸡豚', '山重水复疑无路', '柳暗花明又一村'] },
  { emoji: '📖', title: '观书有感', author: '朱熹', dynasty: '宋', cat: '哲理', bg: 'philosophy', lines: ['半亩方塘一鉴开', '天光云影共徘徊', '问渠那得清如许', '为有源头活水来'] },
  { emoji: '🪷', title: '爱莲说', author: '周敦颐', dynasty: '宋', cat: '哲理', bg: 'philosophy', lines: ['出淤泥而不染', '濯清涟而不妖', '中通外直', '不蔓不枝'] },
  { emoji: '⏰', title: '明日歌', author: '钱鹤滩', dynasty: '清', cat: '哲理', bg: 'philosophy', lines: ['明日复明日', '明日何其多', '我生待明日', '万事成蹉跎'] },
  { emoji: '📚', title: '劝学', author: '颜真卿', dynasty: '唐', cat: '哲理', bg: 'philosophy', lines: ['三更灯火五更鸡', '正是男儿读书时', '黑发不知勤学早', '白首方悔读书迟'] },
  { emoji: '🧗', title: '望岳', author: '杜甫', dynasty: '唐', cat: '哲理', bg: 'landscape', lines: ['岱宗夫如何', '齐鲁青未了', '造化钟神秀', '阴阳割昏晓'] },
  { emoji: '🌊', title: '长歌行', author: '汉乐府', dynasty: '汉', cat: '哲理', bg: 'philosophy', lines: ['百川东到海', '何时复西归', '少壮不努力', '老大徒伤悲'] },
  { emoji: '🎋', title: '竹石', author: '郑燮', dynasty: '清', cat: '哲理', bg: 'philosophy', lines: ['咬定青山不放松', '立根原在破岩中', '千磨万击还坚劲', '任尔东西南北风'] },

  // ===== 节日篇 (8) =====
  { emoji: '🎆', title: '元日', author: '王安石', dynasty: '宋', cat: '节日', bg: 'festive', lines: ['爆竹声中一岁除', '春风送暖入屠苏', '千门万户曈曈日', '总把新桃换旧符'] },
  { emoji: '🌙', title: '中秋月', author: '苏轼', dynasty: '宋', cat: '节日', bg: 'festive', lines: ['暮云收尽溢清寒', '银汉无声转玉盘', '此生此夜不长好', '明月明年何处看'] },
  { emoji: '🎑', title: '十五夜望月', author: '王建', dynasty: '唐', cat: '节日', bg: 'festive', lines: ['中庭地白树栖鸦', '冷露无声湿桂花', '今夜月明人尽望', '不知秋思落谁家'] },
  { emoji: '🎊', title: '清明', author: '杜牧', dynasty: '唐', cat: '节日', bg: 'spring', lines: ['清明时节雨纷纷', '路上行人欲断魂', '借问酒家何处有', '牧童遥指杏花村'] },
  { emoji: '🐉', title: '端午', author: '文秀', dynasty: '唐', cat: '节日', bg: 'festive', lines: ['节分端午自谁言', '万古传闻为屈原', '堪笑楚江空渺渺', '不能洗得直臣冤'] },
  { emoji: '🌉', title: '七夕', author: '林杰', dynasty: '唐', cat: '节日', bg: 'festive', lines: ['七夕今宵看碧霄', '牵牛织女渡河桥', '家家乞巧望秋月', '穿尽红丝几万条'] },
  { emoji: '🏮', title: '正月十五夜', author: '苏味道', dynasty: '唐', cat: '节日', bg: 'festive', lines: ['火树银花合', '星桥铁锁开', '暗尘随马去', '明月逐人来'] },
  { emoji: '🎋', title: '寒食', author: '韩翃', dynasty: '唐', cat: '节日', bg: 'spring', lines: ['春城无处不飞花', '寒食东风御柳斜', '日暮汉宫传蜡烛', '轻烟散入五侯家'] },

  // ===== 童趣篇 (8) =====
  { emoji: '👶', title: '池上', author: '白居易', dynasty: '唐', cat: '童趣', bg: 'summer', lines: ['小娒撑小艇', '偷采白莲回', '不解藏踪迹', '浮萍一道开'] },
  { emoji: '🎣', title: '小儿垂钓', author: '胡令能', dynasty: '唐', cat: '童趣', bg: 'pastoral', lines: ['蓬头稚子学垂纶', '侧坐莓苔草映身', '路人借问遥招手', '怕得鱼惊不应人'] },
  { emoji: '🪁', title: '村居', author: '高鼎', dynasty: '清', cat: '童趣', bg: 'spring', lines: ['草长莺飞二月天', '拂堤杨柳醉春烟', '儿童散学归来早', '忙趁东风放纸鸢'] },
  { emoji: '🦋', title: '宿新市徐公店', author: '杨万里', dynasty: '宋', cat: '童趣', bg: 'pastoral', lines: ['篱落疏疏一径深', '树头新绿未成阴', '儿童急走追黄蝶', '飞入菜花无处寻'] },
  { emoji: '🐂', title: '牧童', author: '吕岩', dynasty: '唐', cat: '童趣', bg: 'pastoral', lines: ['草铺横野六七里', '笛弄晚风三四声', '归来饱饭黄昏后', '不脱蓑衣卧月明'] },
  { emoji: '🎵', title: '所见', author: '袁枚', dynasty: '清', cat: '童趣', bg: 'summer', lines: ['牧童骑黄牛', '歌声振林樾', '意欲捕鸣蝉', '忽然闭口立'] },
  { emoji: '🧒', title: '幼女词', author: '施肩吾', dynasty: '唐', cat: '童趣', bg: 'night', lines: ['幼女才六岁', '未知巧与拙', '向夜在堂前', '学人拜新月'] },
  { emoji: '📚', title: '读书', author: '陆游', dynasty: '宋', cat: '童趣', bg: 'philosophy', lines: ['归老宁无五亩园', '读书本意在元元', '灯前目力虽非昔', '犹课蝇头二万言'] },

  // ===== 花卉篇 (5) =====
  { emoji: '🌺', title: '桃花', author: '周朴', dynasty: '唐', cat: '花卉', bg: 'spring', lines: ['桃花春色暖先开', '明媚谁人不看来', '可惜狂风吹落后', '殷红片片点莓苔'] },
  { emoji: '🌸', title: '江畔独步寻花', author: '杜甫', dynasty: '唐', cat: '花卉', bg: 'spring', lines: ['黄四娘家花满蹊', '千朵万朵压枝低', '留连戏蝶时时舞', '自在娇莺恰恰啼'] },
  { emoji: '🌷', title: '赏牡丹', author: '刘禹锡', dynasty: '唐', cat: '花卉', bg: 'spring', lines: ['庭前芍药妖无格', '池上芙蕖净少情', '唯有牡丹真国色', '花开时节动京城'] },
  { emoji: '🌹', title: '月季', author: '苏轼', dynasty: '宋', cat: '花卉', bg: 'spring', lines: ['花落花开无间断', '春来春去不相关', '牡丹最贵惟春晚', '芍药虽繁只夏初'] },
  { emoji: '💐', title: '兰花', author: '佚名', dynasty: '佚名', cat: '花卉', bg: 'philosophy', lines: ['芝兰生于深林', '不以无人而不芳', '君子修道立德', '不以困穷而改节'] },

  // ===== 励志篇 (8) =====
  { emoji: '💪', title: '龟虽寿（节选）', author: '曹操', dynasty: '汉', cat: '励志', bg: 'philosophy', lines: ['老骥伏枥', '志在千里', '烈士暮年', '壮心不已'] },
  { emoji: '⛰️', title: '望岳', author: '杜甫', dynasty: '唐', cat: '励志', bg: 'landscape', lines: ['会当凌绝顶', '一览众山小', '荡胸生层云', '决眦入归鸟'] },
  { emoji: '🌊', title: '行路难', author: '李白', dynasty: '唐', cat: '励志', bg: 'water', lines: ['长风破浪会有时', '直挂云帆济沧海', '闲来垂钓碧溪上', '忽复乘舟梦日边'] },
  { emoji: '🚀', title: '上李邕', author: '李白', dynasty: '唐', cat: '励志', bg: 'landscape', lines: ['大鹏一日同风起', '扶摇直上九万里', '假令风歇时下来', '犹能簸却沧溟水'] },
  { emoji: '⚔️', title: '满江红（节选）', author: '岳飞', dynasty: '宋', cat: '励志', bg: 'patriotic', lines: ['怒发冲冠', '凭栏处', '潇潇雨歇', '三十功名尘与土'] },
  { emoji: '💎', title: '玉不琢', author: '佚名', dynasty: '佚名', cat: '励志', bg: 'philosophy', lines: ['玉不琢，不成器', '人不学，不知义', '为人子，方少时', '亲师友，习礼仪'] },
  { emoji: '🌊', title: '浪淘沙', author: '刘禹锡', dynasty: '唐', cat: '励志', bg: 'philosophy', lines: ['千淘万漉虽辛苦', '吹尽狂沙始到金', '莫道谗言如浪深', '莫言迁客似沙沉'] },
  { emoji: '🌟', title: '小松', author: '杜荀鹤', dynasty: '唐', cat: '励志', bg: 'nature', lines: ['自小刺头深草里', '而今渐觉出蓬蒿', '时人不识凌云木', '直待凌云始道高'] },

  // ===== 爱国篇 (8) =====
  { emoji: '🏛️', title: '示儿', author: '陆游', dynasty: '宋', cat: '爱国', bg: 'patriotic', lines: ['死去元知万事空', '但悲不见九州同', '王师北定中原日', '家祭无忘告乃翁'] },
  { emoji: '❤️', title: '春望', author: '杜甫', dynasty: '唐', cat: '爱国', bg: 'patriotic', lines: ['国破山河在', '城春草木深', '感时花溅泪', '恨别鸟惊心'] },
  { emoji: '⚔️', title: '过零丁洋', author: '文天祥', dynasty: '宋', cat: '爱国', bg: 'patriotic', lines: ['人生自古谁无死', '留取丹心照汗青', '惶恐滩头说惶恐', '零丁洋里叹零丁'] },
  { emoji: '🏔️', title: '己亥杂诗', author: '龚自珍', dynasty: '清', cat: '爱国', bg: 'patriotic', lines: ['浩荡离愁白日斜', '吟鞭东指即天涯', '落红不是无情物', '化作春泥更护花'] },
  { emoji: '🌙', title: '泊秦淮', author: '杜牧', dynasty: '唐', cat: '爱国', bg: 'night', lines: ['烟笼寒水月笼沙', '夜泊秦淮近酒家', '商女不知亡国恨', '隔江犹唱后庭花'] },
  { emoji: '🏯', title: '金陵图', author: '韦庄', dynasty: '唐', cat: '爱国', bg: 'patriotic', lines: ['谁谓伤心画不成', '画人心逐世人情', '君看六幅南朝事', '老木寒云满故城'] },
  { emoji: '🏛️', title: '蜀相', author: '杜甫', dynasty: '唐', cat: '爱国', bg: 'patriotic', lines: ['丞相祠堂何处寻', '锦官城外柏森森', '映阶碧草自春色', '隔叶黄鹂空好音'] },
  { emoji: '📜', title: '离骚（节选）', author: '屈原', dynasty: '先秦', cat: '爱国', bg: 'patriotic', lines: ['路漫漫其修远兮', '吾将上下而求索', '长太息以掩涕兮', '哀民生之多艰'] },

  // ===== 送别篇 (8) =====
  { emoji: '🎋', title: '赠别', author: '杜牧', dynasty: '唐', cat: '送别', bg: 'autumn', lines: ['多情却似总无情', '唯觉樽前笑不成', '蜡烛有心还惜别', '替人垂泪到天明'] },
  { emoji: '🌿', title: '送别', author: '李叔同', dynasty: '近代', cat: '送别', bg: 'autumn', lines: ['长亭外，古道边', '芳草碧连天', '晚风拂柳笛声残', '夕阳山外山'] },
  { emoji: '🌸', title: '送魏二', author: '王昌龄', dynasty: '唐', cat: '送别', bg: 'autumn', lines: ['醉别江楼橘柚香', '江风引雨入舟凉', '忆君遥在潇湘月', '愁听清猿梦里长'] },
  { emoji: '🌊', title: '送人东游', author: '温庭筠', dynasty: '唐', cat: '送别', bg: 'autumn', lines: ['荒戍落黄叶', '浩然离故关', '高风汉阳渡', '初日郢门山'] },
  { emoji: '🌙', title: '送杜十四之江南', author: '孟浩然', dynasty: '唐', cat: '送别', bg: 'water', lines: ['荆吴相接水为乡', '君去春江正淼茫', '日暮征帆何处泊', '天涯一望断人肠'] },
  { emoji: '🍃', title: '送友人入蜀', author: '李白', dynasty: '唐', cat: '送别', bg: 'landscape', lines: ['见说蚕丛路', '崎岖不易行', '山从人面起', '云傍马头生'] },
  { emoji: '🌉', title: '重送裴郎中贬吉州', author: '刘长卿', dynasty: '唐', cat: '送别', bg: 'water', lines: ['猿啼客散暮江头', '人自伤心水自流', '同作逐臣君更远', '青山万里一孤舟'] },
  { emoji: '🎍', title: '送李判官之润州行营', author: '刘长卿', dynasty: '唐', cat: '送别', bg: 'frontier', lines: ['万里辞家事鼓鼙', '金陵驿路楚云西', '江春不肯留归客', '草色青青送马蹄'] },

  // ===== 闲适篇 (8) =====
  { emoji: '☕', title: '饮酒', author: '陶渊明', dynasty: '魏晋', cat: '闲适', bg: 'pastoral', lines: ['结庐在人境', '而无车马喧', '问君何能尔', '心远地自偏'] },
  { emoji: '🌿', title: '清平乐·村居', author: '辛弃疾', dynasty: '宋', cat: '闲适', bg: 'pastoral', lines: ['茅檐低小', '溪上青青草', '醉里吴音相媚好', '白发谁家翁媪'] },
  { emoji: '🛶', title: '滁州西涧', author: '韦应物', dynasty: '唐', cat: '闲适', bg: 'water', lines: ['独怜幽草涧边生', '上有黄鹂深树鸣', '春潮带雨晚来急', '野渡无人舟自横'] },
  { emoji: '🎣', title: '江村即事', author: '司空曙', dynasty: '唐', cat: '闲适', bg: 'water', lines: ['钓罢归来不系船', '江村月落正堪眠', '纵然一夜风吹去', '只在芦花浅水边'] },
  { emoji: '🏞️', title: '书湖阴先生壁', author: '王安石', dynasty: '宋', cat: '闲适', bg: 'pastoral', lines: ['茅檐长扫净无苔', '花木成畦手自栽', '一水护田将绿绕', '两山排闼送青来'] },
  { emoji: '🌺', title: '夏意', author: '苏舜钦', dynasty: '宋', cat: '闲适', bg: 'summer', lines: ['别院深深夏簟清', '石榴开遍透帘明', '树阴满地日当午', '梦觉流莺时一声'] },
  { emoji: '🍵', title: '山家', author: '张继', dynasty: '唐', cat: '闲适', bg: 'pastoral', lines: ['板桥人渡泉声', '茅檐日午鸡鸣', '莫嗔焙茶烟暗', '却喜晒谷天晴'] },
  { emoji: '🌾', title: '田舍', author: '范成大', dynasty: '宋', cat: '闲适', bg: 'pastoral', lines: ['呼唤携锄至', '安排筑圃忙', '儿童眠落叶', '鸟雀噪斜阳'] },
];
