export const allPoems = [
  { emoji: '🦆', title: '咏鹅', author: '骆宾王', dynasty: '唐', cat: '咏物', bg: 'nature', lines: ['鹅，鹅，鹅', '曲项向天歌', '白毛浮绿水', '红掌拨清波'] },
  { emoji: '🌿', title: '咏柳', author: '贺知章', dynasty: '唐', cat: '咏物', bg: 'spring', lines: ['碧玉妆成一树高', '万条垂下绿丝绦', '不知细叶谁裁出', '二月春风似剪刀'] },
  { emoji: '🐝', title: '蜂', author: '罗隐', dynasty: '唐', cat: '咏物', bg: 'nature', lines: ['不论平地与山尖', '无限风光尽被占', '采得百花成蜜后', '为谁辛苦为谁甜'] },
  { emoji: '🖼️', title: '画', author: '王维', dynasty: '唐', cat: '咏物', bg: 'landscape', lines: ['远看山有色', '近听水无声', '春去花还在', '人来鸟不惊'] },
  { emoji: '🌺', title: '梅花', author: '王安石', dynasty: '宋', cat: '咏物', bg: 'winter', lines: ['墙角数枝梅', '凌寒独自开', '遥知不是雪', '为有暗香来'] },
  { emoji: '🎋', title: '竹石', author: '郑燮', dynasty: '清', cat: '咏物', bg: 'nature', lines: ['咬定青山不放松', '立根原在破岩中', '千磨万击还坚劲', '任尔东西南北风'] },
  { emoji: '🌬️', title: '风', author: '李峤', dynasty: '唐', cat: '咏物', bg: 'nature', lines: ['解落三秋叶', '能开二月花', '过江千尺浪', '入竹万竿斜'] },
  { emoji: '🌼', title: '菊花', author: '元稹', dynasty: '唐', cat: '咏物', bg: 'autumn', lines: ['秋丛绕舍似陶家', '遍绕篱边日渐斜', '不是花中偏爱菊', '此花开尽更无花'] },
  { emoji: '🪨', title: '石灰吟', author: '于谦', dynasty: '明', cat: '咏物', bg: 'philosophy', lines: ['千锤万凿出深山', '烈火焚烧若等闲', '粉骨碎身浑不怕', '要留清白在人间'] },
  { emoji: '💎', title: '墨梅', author: '王冕', dynasty: '元', cat: '咏物', bg: 'winter', lines: ['吾家洗砚池头树', '朵朵花开淡墨痕', '不要人夸好颜色', '只留清气满乾坤'] },
  { emoji: '🪷', title: '小池', author: '杨万里', dynasty: '宋', cat: '咏物', bg: 'summer', lines: ['泉眼无声惜细流', '树阴照水爱晴柔', '小荷才露尖尖角', '早有蜻蜓立上头'] },
  { emoji: '🌲', title: '青松', author: '陈毅', dynasty: '现代', cat: '咏物', bg: 'winter', lines: ['大雪压青松', '青松挺且直', '要知松高洁', '待到雪化时'] },
  { emoji: '☁️', title: '白云泉', author: '白居易', dynasty: '唐', cat: '咏物', bg: 'landscape', lines: ['天平山上白云泉', '云自无心水自闲', '何必奔冲山下去', '更添波浪向人间'] },
  { emoji: '🌊', title: '浪淘沙', author: '刘禹锡', dynasty: '唐', cat: '咏物', bg: 'water', lines: ['九曲黄河万里沙', '浪淘风簸自天涯', '如今直上银河去', '同到牵牛织女家'] },
  { emoji: '🍃', title: '落叶', author: '孔绍安', dynasty: '唐', cat: '咏物', bg: 'autumn', lines: ['早秋惊落叶', '飘零似客心', '翻飞未肯下', '犹言惜故林'] },
  { emoji: '⛰️', title: '望庐山瀑布', author: '李白', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['日照香炉生紫烟', '遥看瀑布挂前川', '飞流直下三千尺', '疑是银河落九天'] },
  { emoji: '🏔️', title: '望天门山', author: '李白', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['天门中断楚江开', '碧水东流至此回', '两岸青山相对出', '孤帆一片日边来'] },
  { emoji: '🏞️', title: '早发白帝城', author: '李白', dynasty: '唐', cat: '山水', bg: 'water', lines: ['朝辞白帝彩云间', '千里江陵一日还', '两岸猿声啼不住', '轻舟已过万重山'] },
  { emoji: '🌄', title: '登鹳雀楼', author: '王之涣', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['白日依山尽', '黄河入海流', '欲穷千里目', '更上一层楼'] },
  { emoji: '🏯', title: '黄鹤楼送孟浩然之广陵', author: '李白', dynasty: '唐', cat: '山水', bg: 'water', lines: ['故人西辞黄鹤楼', '烟花三月下扬州', '孤帆远影碧空尽', '唯见长江天际流'] },
  { emoji: '🌅', title: '忆江南', author: '白居易', dynasty: '唐', cat: '山水', bg: 'spring', lines: ['江南好', '风景旧曾谙', '日出江花红胜火', '春来江水绿如蓝'] },
  { emoji: '🏔️', title: '山行', author: '杜牧', dynasty: '唐', cat: '山水', bg: 'autumn', lines: ['远上寒山石径斜', '白云生处有人家', '停车坐爱枫林晚', '霜叶红于二月花'] },
  { emoji: '🌋', title: '题西林壁', author: '苏轼', dynasty: '宋', cat: '山水', bg: 'landscape', lines: ['横看成岭侧成峰', '远近高低各不同', '不识庐山真面目', '只缘身在此山中'] },
  { emoji: '💦', title: '饮湖上初晴后雨', author: '苏轼', dynasty: '宋', cat: '山水', bg: 'water', lines: ['水光潋滟晴方好', '山色空蒙雨亦奇', '欲把西湖比西子', '淡妆浓抹总相宜'] },
  { emoji: '🌊', title: '观沧海', author: '曹操', dynasty: '汉', cat: '山水', bg: 'water', lines: ['东临碣石', '以观沧海', '水何澹澹', '山岛竦峙'] },
  { emoji: '🏜️', title: '凉州词', author: '王之涣', dynasty: '唐', cat: '山水', bg: 'frontier', lines: ['黄河远上白云间', '一片孤城万仞山', '羌笛何须怨杨柳', '春风不度玉门关'] },
  { emoji: '🏞️', title: '鹿柴', author: '王维', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['空山不见人', '但闻人语响', '返景入深林', '复照青苔上'] },
  { emoji: '🏔️', title: '独坐敬亭山', author: '李白', dynasty: '唐', cat: '山水', bg: 'landscape', lines: ['众鸟高飞尽', '孤云独去闲', '相看两不厌', '只有敬亭山'] },
  { emoji: '🌉', title: '枫桥夜泊', author: '张继', dynasty: '唐', cat: '山水', bg: 'night', lines: ['月落乌啼霜满天', '江枫渔火对愁眠', '姑苏城外寒山寺', '夜半钟声到客船'] },
  { emoji: '🏝️', title: '鸟鸣涧', author: '王维', dynasty: '唐', cat: '山水', bg: 'night', lines: ['人闲桂花落', '夜静春山空', '月出惊山鸟', '时鸣春涧中'] },
  { emoji: '🌸', title: '春晓', author: '孟浩然', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['春眠不觉晓', '处处闻啼鸟', '夜来风雨声', '花落知多少'] },
  { emoji: '🌱', title: '春夜喜雨', author: '杜甫', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['好雨知时节', '当春乃发生', '随风潜入夜', '润物细无声'] },
  { emoji: '🌿', title: '钱塘湖春行', author: '白居易', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['孤山寺北贾亭西', '水面初平云脚低', '几处早莺争暖树', '谁家新燕啄春泥'] },
  { emoji: '🌸', title: '江南春', author: '杜牧', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['千里莺啼绿映红', '水村山郭酒旗风', '南朝四百八十寺', '多少楼台烟雨中'] },
  { emoji: '🌻', title: '夏日绝句', author: '李清照', dynasty: '宋', cat: '四季', bg: 'summer', lines: ['生当作人杰', '死亦为鬼雄', '至今思项羽', '不肯过江东'] },
  { emoji: '☀️', title: '晓出净慈寺送林子方', author: '杨万里', dynasty: '宋', cat: '四季', bg: 'summer', lines: ['毕竟西湖六月中', '风光不与四时同', '接天莲叶无穷碧', '映日荷花别样红'] },
  { emoji: '🌾', title: '悯农·其一', author: '李绅', dynasty: '唐', cat: '四季', bg: 'summer', lines: ['春种一粒粟', '秋收万颗子', '四海无闲田', '农夫犹饿死'] },
  { emoji: '🌾', title: '悯农·其二', author: '李绅', dynasty: '唐', cat: '四季', bg: 'summer', lines: ['锄禾日当午', '汗滴禾下土', '谁知盘中餐', '粒粒皆辛苦'] },
  { emoji: '🍂', title: '秋夕', author: '杜牧', dynasty: '唐', cat: '四季', bg: 'autumn', lines: ['银烛秋光冷画屏', '轻罗小扇扑流萤', '天阶夜色凉如水', '卧看牵牛织女星'] },
  { emoji: '🍁', title: '山居秋暝', author: '王维', dynasty: '唐', cat: '四季', bg: 'autumn', lines: ['空山新雨后', '天气晚来秋', '明月松间照', '清泉石上流'] },
  { emoji: '🌨️', title: '雪梅', author: '卢梅坡', dynasty: '宋', cat: '四季', bg: 'winter', lines: ['梅雪争春未肯降', '骚人阁笔费评章', '梅须逊雪三分白', '雪却输梅一段香'] },
  { emoji: '🌸', title: '大林寺桃花', author: '白居易', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['人间四月芳菲尽', '山寺桃花始盛开', '长恨春归无觅处', '不知转入此中来'] },
  { emoji: '🌿', title: '村居', author: '高鼎', dynasty: '清', cat: '四季', bg: 'spring', lines: ['草长莺飞二月天', '拂堤杨柳醉春烟', '儿童散学归来早', '忙趁东风放纸鸢'] },
  { emoji: '🍂', title: '暮江吟', author: '白居易', dynasty: '唐', cat: '四季', bg: 'autumn', lines: ['一道残阳铺水中', '半江瑟瑟半江红', '可怜九月初三夜', '露似真珠月似弓'] },
  { emoji: '🌺', title: '游园不值', author: '叶绍翁', dynasty: '宋', cat: '四季', bg: 'spring', lines: ['应怜屐齿印苍苔', '小扣柴扉久不开', '春色满园关不住', '一枝红杏出墙来'] },
  { emoji: '🏡', title: '过故人庄', author: '孟浩然', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['故人具鸡黍', '邀我至田家', '绿树村边合', '青山郭外斜'] },
  { emoji: '🌾', title: '四时田园杂兴', author: '范成大', dynasty: '宋', cat: '田园', bg: 'pastoral', lines: ['昼出耘田夜绩麻', '村庄儿女各当家', '童孙未解供耕织', '也傍桑阴学种瓜'] },
  { emoji: '🐂', title: '田园乐', author: '王维', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['萋萋春草秋绿', '落落长松夏寒', '牛羊自归村巷', '童稚不识衣冠'] },
  { emoji: '🌻', title: '宿新市徐公店', author: '杨万里', dynasty: '宋', cat: '田园', bg: 'pastoral', lines: ['篱落疏疏一径深', '树头新绿未成阴', '儿童急走追黄蝶', '飞入菜花无处寻'] },
  { emoji: '🐔', title: '归园田居', author: '陶渊明', dynasty: '魏晋', cat: '田园', bg: 'pastoral', lines: ['种豆南山下', '草盛豆苗稀', '晨兴理荒秽', '带月荷锄归'] },
  { emoji: '🐑', title: '牧童', author: '吕岩', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['草铺横野六七里', '笛弄晚风三四声', '归来饱饭黄昏后', '不脱蓑衣卧月明'] },
  { emoji: '🎋', title: '竹里馆', author: '王维', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['独坐幽篁里', '弹琴复长啸', '深林人不知', '明月来相照'] },
  { emoji: '🌿', title: '寻隐者不遇', author: '贾岛', dynasty: '唐', cat: '田园', bg: 'landscape', lines: ['松下问童子', '言师采药去', '只在此山中', '云深不知处'] },
  { emoji: '🌸', title: '桃花源记（节选）', author: '陶渊明', dynasty: '魏晋', cat: '田园', bg: 'pastoral', lines: ['忽逢桃花林', '夹岸数百步', '中无杂树', '芳草鲜美'] },
  { emoji: '🏡', title: '渭川田家', author: '王维', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['斜阳照墟落', '穷巷牛羊归', '野老念牧童', '倚杖候荆扉'] },
  { emoji: '🐟', title: '渔歌子', author: '张志和', dynasty: '唐', cat: '田园', bg: 'water', lines: ['西塞山前白鹭飞', '桃花流水鳜鱼肥', '青箬笠，绿蓑衣', '斜风细雨不须归'] },
  { emoji: '🌾', title: '田上', author: '聂夷中', dynasty: '唐', cat: '田园', bg: 'pastoral', lines: ['父耕原上田', '子劚山下荒', '六月禾未秀', '官家已修仓'] },
  { emoji: '🌙', title: '静夜思', author: '李白', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['床前明月光', '疑是地上霜', '举头望明月', '低头思故乡'] },
  { emoji: '🏠', title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', cat: '思乡', bg: 'autumn', lines: ['独在异乡为异客', '每逢佳节倍思亲', '遥知兄弟登高处', '遍插茱萸少一人'] },
  { emoji: '🕊️', title: '回乡偶书', author: '贺知章', dynasty: '唐', cat: '思乡', bg: 'spring', lines: ['少小离家老大回', '乡音无改鬓毛衰', '儿童相见不相识', '笑问客从何处来'] },
  { emoji: '🌅', title: '渡汉江', author: '宋之问', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['岭外音书断', '经冬复历春', '近乡情更怯', '不敢问来人'] },
  { emoji: '🌙', title: '月夜忆舍弟', author: '杜甫', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['戍鼓断人行', '边秋一雁声', '露从今夜白', '月是故乡明'] },
  { emoji: '🏔️', title: '杂诗', author: '王维', dynasty: '唐', cat: '思乡', bg: 'winter', lines: ['君自故乡来', '应知故乡事', '来日绮窗前', '寒梅著花未'] },
  { emoji: '💌', title: '逢入京使', author: '岑参', dynasty: '唐', cat: '思乡', bg: 'frontier', lines: ['故园东望路漫漫', '双袖龙钟泪不干', '马上相逢无纸笔', '凭君传语报平安'] },
  { emoji: '🌊', title: '次北固山下', author: '王湾', dynasty: '唐', cat: '思乡', bg: 'water', lines: ['客路青山外', '行舟绿水前', '潮平两岸阔', '风正一帆悬'] },
  { emoji: '🌙', title: '峨眉山月歌', author: '李白', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['峨眉山月半轮秋', '影入平羌江水流', '夜发清溪向三峡', '思君不见下渝州'] },
  { emoji: '🕯️', title: '夜雨寄北', author: '李商隐', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['君问归期未有期', '巴山夜雨涨秋池', '何当共剪西窗烛', '却话巴山夜雨时'] },
  { emoji: '🌉', title: '宿建德江', author: '孟浩然', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['移舟泊烟渚', '日暮客愁新', '野旷天低树', '江清月近人'] },
  { emoji: '🌨️', title: '除夜作', author: '高适', dynasty: '唐', cat: '思乡', bg: 'winter', lines: ['旅馆寒灯独不眠', '客心何事转凄然', '故乡今夜思千里', '霜鬓明朝又一年'] },
  { emoji: '📜', title: '长歌行', author: '汉乐府', dynasty: '汉', cat: '劝学', bg: 'spring', lines: ['青青园中葵', '朝露待日晞', '阳春布德泽', '万物生光辉', '常恐秋节至', '焜黄华叶衰', '百川东到海', '何时复西归', '少壮不努力', '老大徒伤悲'] },
  { emoji: '📖', title: '劝学', author: '颜真卿', dynasty: '唐', cat: '劝学', bg: 'spring', lines: ['三更灯火五更鸡', '正是男儿读书时', '黑发不知勤学早', '白首方悔读书迟'] },
  { emoji: '📚', title: '冬夜读书示子聿', author: '陆游', dynasty: '宋', cat: '劝学', bg: 'winter', lines: ['古人学问无遗力', '少壮工夫老始成', '纸上得来终觉浅', '绝知此事要躬行'] },
  { emoji: '📝', title: '观书有感', author: '朱熹', dynasty: '宋', cat: '劝学', bg: 'water', lines: ['半亩方塘一鉴开', '天光云影共徘徊', '问渠那得清如许', '为有源头活水来'] },
  { emoji: '🎯', title: '竹石', author: '郑燮', dynasty: '清', cat: '劝学', bg: 'nature', lines: ['咬定青山不放松', '立根原在破岩中', '千磨万击还坚劲', '任尔东西南北风'] },
  { emoji: '💪', title: '夏日绝句', author: '李清照', dynasty: '宋', cat: '劝学', bg: 'summer', lines: ['生当作人杰', '死亦为鬼雄', '至今思项羽', '不肯过江东'] },
  { emoji: '🏆', title: '登鹳雀楼', author: '王之涣', dynasty: '唐', cat: '劝学', bg: 'landscape', lines: ['白日依山尽', '黄河入海流', '欲穷千里目', '更上一层楼'] },
  { emoji: '🦅', title: '题西林壁', author: '苏轼', dynasty: '宋', cat: '劝学', bg: 'landscape', lines: ['横看成岭侧成峰', '远近高低各不同', '不识庐山真面目', '只缘身在此山中'] },
  { emoji: '🍷', title: '将进酒（节选）', author: '李白', dynasty: '唐', cat: '豪情', bg: 'landscape', lines: ['君不见黄河之水天上来', '奔流到海不复回', '君不见高堂明镜悲白发', '朝如青丝暮成雪'] },
  { emoji: '🗡️', title: '凉州词（其一）', author: '王翰', dynasty: '唐', cat: '豪情', bg: 'frontier', lines: ['葡萄美酒夜光杯', '欲饮琵琶马上催', '醉卧沙场君莫笑', '古来征战几人回'] },
  { emoji: '🏇', title: '出塞', author: '王昌龄', dynasty: '唐', cat: '豪情', bg: 'frontier', lines: ['秦时明月汉时关', '万里长征人未还', '但使龙城飞将在', '不教胡马度阴山'] },
  { emoji: '⚔️', title: '从军行', author: '王昌龄', dynasty: '唐', cat: '豪情', bg: 'frontier', lines: ['青海长云暗雪山', '孤城遥望玉门关', '黄沙百战穿金甲', '不破楼兰终不还'] },
  { emoji: '🌊', title: '浪淘沙（其七）', author: '刘禹锡', dynasty: '唐', cat: '豪情', bg: 'water', lines: ['八月涛声吼地来', '头高数丈触山回', '须臾却入海门去', '卷起沙堆似雪堆'] },
  { emoji: '🐎', title: '塞下曲', author: '卢纶', dynasty: '唐', cat: '豪情', bg: 'frontier', lines: ['月黑雁飞高', '单于夜遁逃', '欲将轻骑逐', '大雪满弓刀'] },
  { emoji: '🏔️', title: '望岳', author: '杜甫', dynasty: '唐', cat: '豪情', bg: 'landscape', lines: ['岱宗夫如何', '齐鲁青未了', '造化钟神秀', '阴阳割昏晓', '荡胸生曾云', '决眦入归鸟', '会当凌绝顶', '一览众山小'] },
  { emoji: '🦅', title: '江雪', author: '柳宗元', dynasty: '唐', cat: '山水', bg: 'winter', lines: ['千山鸟飞绝', '万径人踪灭', '孤舟蓑笠翁', '独钓寒江雪'] },
  { emoji: '🎶', title: '绝句（其三）', author: '杜甫', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['两个黄鹂鸣翠柳', '一行白鹭上青天', '窗含西岭千秋雪', '门泊东吴万里船'] },
  { emoji: '🍃', title: '绝句（其一）', author: '杜甫', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['迟日江山丽', '春风花草香', '泥融飞燕子', '沙暖睡鸳鸯'] },
  { emoji: '🎵', title: '绝句（其二）', author: '杜甫', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['江碧鸟逾白', '山青花欲燃', '今春看又过', '何日是归年'] },
  { emoji: '🎐', title: '赠刘景文', author: '苏轼', dynasty: '宋', cat: '四季', bg: 'autumn', lines: ['荷尽已无擎雨盖', '菊残犹有傲霜枝', '一年好景君须记', '最是橙黄橘绿时'] },
  { emoji: '🏯', title: '江南逢李龟年', author: '杜甫', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['岐王宅里寻常见', '崔九堂前几度闻', '正是江南好风景', '落花时节又逢君'] },
  { emoji: '🌉', title: '赠汪伦', author: '李白', dynasty: '唐', cat: '抒情', bg: 'water', lines: ['李白乘舟将欲行', '忽闻岸上踏歌声', '桃花潭水深千尺', '不及汪伦送我情'] },
  { emoji: '🌙', title: '送杜少府之任蜀州', author: '王勃', dynasty: '唐', cat: '抒情', bg: 'landscape', lines: ['城阙辅三秦', '风烟望五津', '与君离别意', '同是宦游人', '海内存知己', '天涯若比邻', '无为在歧路', '儿女共沾巾'] },
  { emoji: '🍃', title: '送元二使安西', author: '王维', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['渭城朝雨浥轻尘', '客舍青青柳色新', '劝君更尽一杯酒', '西出阳关无故人'] },
  { emoji: '🌊', title: '别董大', author: '高适', dynasty: '唐', cat: '抒情', bg: 'winter', lines: ['千里黄云白日曛', '北风吹雁雪纷纷', '莫愁前路无知己', '天下谁人不识君'] },
  { emoji: '🎋', title: '相思', author: '王维', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['红豆生南国', '春来发几枝', '愿君多采撷', '此物最相思'] },
  { emoji: '🌸', title: '春望', author: '杜甫', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['国破山河在', '城春草木深', '感时花溅泪', '恨别鸟惊心', '烽火连三月', '家书抵万金', '白头搔更短', '浑欲不胜簪'] },
  { emoji: '🕯️', title: '无题', author: '李商隐', dynasty: '唐', cat: '抒情', bg: 'night', lines: ['相见时难别亦难', '东风无力百花残', '春蚕到死丝方尽', '蜡炬成灰泪始干'] },
  { emoji: '💧', title: '芙蓉楼送辛渐', author: '王昌龄', dynasty: '唐', cat: '抒情', bg: 'water', lines: ['寒雨连江夜入吴', '平明送客楚山孤', '洛阳亲友如相问', '一片冰心在玉壶'] },
  { emoji: '🏞️', title: '滁州西涧', author: '韦应物', dynasty: '唐', cat: '山水', bg: 'water', lines: ['独怜幽草涧边生', '上有黄鹂深树鸣', '春潮带雨晚来急', '野渡无人舟自横'] },
  { emoji: '🎑', title: '望月怀远', author: '张九龄', dynasty: '唐', cat: '思乡', bg: 'night', lines: ['海上生明月', '天涯共此时', '情人怨遥夜', '竟夕起相思'] },
  { emoji: '🏯', title: '泊船瓜洲', author: '王安石', dynasty: '宋', cat: '思乡', bg: 'water', lines: ['京口瓜洲一水间', '钟山只隔数重山', '春风又绿江南岸', '明月何时照我还'] },
  { emoji: '🌸', title: '春日', author: '朱熹', dynasty: '宋', cat: '四季', bg: 'spring', lines: ['胜日寻芳泗水滨', '无边光景一时新', '等闲识得东风面', '万紫千红总是春'] },
  { emoji: '🌾', title: '江南', author: '汉乐府', dynasty: '汉', cat: '田园', bg: 'summer', lines: ['江南可采莲', '莲叶何田田', '鱼戏莲叶间', '鱼戏莲叶东', '鱼戏莲叶西', '鱼戏莲叶南', '鱼戏莲叶北'] },
  { emoji: '🌸', title: '敕勒歌', author: '北朝民歌', dynasty: '南北朝', cat: '山水', bg: 'landscape', lines: ['敕勒川', '阴山下', '天似穹庐', '笼盖四野', '天苍苍', '野茫茫', '风吹草低见牛羊'] },
  { emoji: '🌅', title: '元日', author: '王安石', dynasty: '宋', cat: '节日', bg: 'festive', lines: ['爆竹声中一岁除', '春风送暖入屠苏', '千门万户曈曈日', '总把新桃换旧符'] },
  { emoji: '🌙', title: '清明', author: '杜牧', dynasty: '唐', cat: '节日', bg: 'spring', lines: ['清明时节雨纷纷', '路上行人欲断魂', '借问酒家何处有', '牧童遥指杏花村'] },
  { emoji: '🥟', title: '除夜雪', author: '陆游', dynasty: '宋', cat: '节日', bg: 'winter', lines: ['北风吹雪四更初', '嘉瑞天教及岁除', '半盏屠苏犹未举', '灯前小草写桃符'] },
  { emoji: '🎆', title: '正月十五夜', author: '苏味道', dynasty: '唐', cat: '节日', bg: 'night', lines: ['火树银花合', '星桥铁锁开', '暗尘随马去', '明月逐人来'] },
  { emoji: '🥮', title: '望月怀远（节选）', author: '张九龄', dynasty: '唐', cat: '节日', bg: 'night', lines: ['海上生明月', '天涯共此时', '情人怨遥夜', '竟夕起相思'] },
  { emoji: '🎊', title: '九月九日忆山东兄弟', author: '王维', dynasty: '唐', cat: '节日', bg: 'autumn', lines: ['独在异乡为异客', '每逢佳节倍思亲', '遥知兄弟登高处', '遍插茱萸少一人'] },
  { emoji: '🎋', title: '端午', author: '文秀', dynasty: '唐', cat: '节日', bg: 'summer', lines: ['节分端午自谁言', '万古传闻为屈原', '堪笑楚江空渺渺', '不能洗得直臣冤'] },
  { emoji: '🌙', title: '嫦娥', author: '李商隐', dynasty: '唐', cat: '神话', bg: 'night', lines: ['云母屏风烛影深', '长河渐落晓星沉', '嫦娥应悔偷灵药', '碧海青天夜夜心'] },
  { emoji: '🌌', title: '乞巧', author: '林杰', dynasty: '唐', cat: '节日', bg: 'night', lines: ['七夕今宵看碧霄', '牵牛织女渡河桥', '家家乞巧望秋月', '穿尽红丝几万条'] },
  { emoji: '🎪', title: '十五夜望月', author: '王建', dynasty: '唐', cat: '节日', bg: 'night', lines: ['中庭地白树栖鸦', '冷露无声湿桂花', '今夜月明人尽望', '不知秋思落谁家'] },
  { emoji: '🍷', title: '月下独酌（节选）', author: '李白', dynasty: '唐', cat: '豪情', bg: 'night', lines: ['花间一壶酒', '独酌无相亲', '举杯邀明月', '对影成三人'] },
  { emoji: '🎭', title: '行路难（节选）', author: '李白', dynasty: '唐', cat: '豪情', bg: 'landscape', lines: ['金樽清酒斗十千', '玉盘珍羞直万钱', '停杯投箸不能食', '拔剑四顾心茫然', '长风破浪会有时', '直挂云帆济沧海'] },
  { emoji: '🏔️', title: '蜀道难（节选）', author: '李白', dynasty: '唐', cat: '豪情', bg: 'landscape', lines: ['噫吁嚱', '危乎高哉', '蜀道之难', '难于上青天'] },
  { emoji: '🎵', title: '琵琶行（节选）', author: '白居易', dynasty: '唐', cat: '抒情', bg: 'night', lines: ['千呼万唤始出来', '犹抱琵琶半遮面', '转轴拨弦三两声', '未成曲调先有情', '大弦嘈嘈如急雨', '小弦切切如私语'] },
  { emoji: '🎶', title: '锦瑟', author: '李商隐', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['锦瑟无端五十弦', '一弦一柱思华年', '庄生晓梦迷蝴蝶', '望帝春心托杜鹃'] },
  { emoji: '🌸', title: '己亥杂诗', author: '龚自珍', dynasty: '清', cat: '爱国', bg: 'spring', lines: ['浩荡离愁白日斜', '吟鞭东指即天涯', '落红不是无情物', '化作春泥更护花'] },
  { emoji: '🏯', title: '示儿', author: '陆游', dynasty: '宋', cat: '爱国', bg: 'winter', lines: ['死去元知万事空', '但悲不见九州同', '王师北定中原日', '家祭无忘告乃翁'] },
  { emoji: '❤️', title: '病起书怀', author: '陆游', dynasty: '宋', cat: '爱国', bg: 'spring', lines: ['病骨支离纱帽宽', '孤臣万里客江干', '位卑未敢忘忧国', '事定犹须待阖棺'] },
  { emoji: '🏛️', title: '过零丁洋', author: '文天祥', dynasty: '宋', cat: '爱国', bg: 'water', lines: ['辛苦遭逢起一经', '干戈寥落四周星', '山河破碎风飘絮', '身世浮沉雨打萍', '惶恐滩头说惶恐', '零丁洋里叹零丁', '人生自古谁无死', '留取丹心照汗青'] },
  { emoji: '⚔️', title: '满江红（节选）', author: '岳飞', dynasty: '宋', cat: '爱国', bg: 'patriotic', lines: ['怒发冲冠', '凭栏处', '潇潇雨歇', '抬望眼', '仰天长啸', '壮怀激烈'] },
  { emoji: '🌅', title: '春望', author: '杜甫', dynasty: '唐', cat: '爱国', bg: 'spring', lines: ['国破山河在', '城春草木深', '感时花溅泪', '恨别鸟惊心', '烽火连三月', '家书抵万金', '白头搔更短', '浑欲不胜簪'] },
  { emoji: '🏯', title: '泊秦淮', author: '杜牧', dynasty: '唐', cat: '爱国', bg: 'night', lines: ['烟笼寒水月笼沙', '夜泊秦淮近酒家', '商女不知亡国恨', '隔江犹唱后庭花'] },
  { emoji: '🗡️', title: '十一月四日风雨大作', author: '陆游', dynasty: '宋', cat: '爱国', bg: 'winter', lines: ['僵卧孤村不自哀', '尚思为国戍轮台', '夜阑卧听风吹雨', '铁马冰河入梦来'] },
  { emoji: '🌸', title: '江南春', author: '杜牧', dynasty: '唐', cat: '山水', bg: 'spring', lines: ['千里莺啼绿映红', '水村山郭酒旗风', '南朝四百八十寺', '多少楼台烟雨中'] },
  { emoji: '🌊', title: '赤壁', author: '杜牧', dynasty: '唐', cat: '咏史', bg: 'water', lines: ['折戟沉沙铁未销', '自将磨洗认前朝', '东风不与周郎便', '铜雀春深锁二乔'] },
  { emoji: '🏛️', title: '登金陵凤凰台', author: '李白', dynasty: '唐', cat: '咏史', bg: 'landscape', lines: ['凤凰台上凤凰游', '虎踞龙盘今胜昔', '吴宫花草埋幽径', '晋代衣冠成古丘'] },
  { emoji: '🏔️', title: '永遇乐·京口北固亭怀古（节选）', author: '辛弃疾', dynasty: '宋', cat: '咏史', bg: 'landscape', lines: ['千古江山', '英雄无觅', '孙仲谋处', '舞榭歌台', '风流总被', '雨打风吹去'] },
  { emoji: '🌿', title: '赋得古原草送别', author: '白居易', dynasty: '唐', cat: '咏物', bg: 'spring', lines: ['离离原上草', '一岁一枯荣', '野火烧不尽', '春风吹又生', '远芳侵古道', '晴翠接荒城', '又送王孙去', '萋萋满别情'] },
  { emoji: '🌺', title: '游子吟', author: '孟郊', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['慈母手中线', '游子身上衣', '临行密密缝', '意恐迟迟归', '谁言寸草心', '报得三春晖'] },
  { emoji: '🎵', title: '七步诗', author: '曹植', dynasty: '三国', cat: '咏物', bg: 'spring', lines: ['煮豆燃豆萁', '豆在釜中泣', '本是同根生', '相煎何太急'] },
  { emoji: '🏯', title: '乌衣巷', author: '刘禹锡', dynasty: '唐', cat: '咏史', bg: 'spring', lines: ['朱雀桥边野草花', '乌衣巷口夕阳斜', '旧时王谢堂前燕', '飞入寻常百姓家'] },
  { emoji: '🌸', title: '题临安邸', author: '林升', dynasty: '宋', cat: '爱国', bg: 'spring', lines: ['山外青山楼外楼', '西湖歌舞几时休', '暖风熏得游人醉', '直把杭州作汴州'] },
  { emoji: '🌙', title: '水调歌头（节选）', author: '苏轼', dynasty: '宋', cat: '豪情', bg: 'night', lines: ['明月几时有', '把酒问青天', '不知天上宫阙', '今夕是何年', '但愿人长久', '千里共婵娟'] },
  { emoji: '⛰️', title: '题李凝幽居（节选）', author: '贾岛', dynasty: '唐', cat: '田园', bg: 'landscape', lines: ['闲居少邻并', '草径入荒园', '鸟宿池边树', '僧敲月下门'] },
  { emoji: '🕊️', title: '使至塞上', author: '王维', dynasty: '唐', cat: '山水', bg: 'frontier', lines: ['单车欲问边', '属国过居延', '征蓬出汉塞', '归雁入胡天', '大漠孤烟直', '长河落日圆', '萧关逢候骑', '都护在燕然'] },
  { emoji: '🦆', title: '惠崇春江晚景', author: '苏轼', dynasty: '宋', cat: '四季', bg: 'spring', lines: ['竹外桃花三两枝', '春江水暖鸭先知', '蒌蒿满地芦芽短', '正是河豚欲上时'] },
  { emoji: '🎋', title: '早春呈水部张十八员外', author: '韩愈', dynasty: '唐', cat: '四季', bg: 'spring', lines: ['天街小雨润如酥', '草色遥看近却无', '最是一年春好处', '绝胜烟柳满皇都'] },
  { emoji: '🌾', title: '观刈麦（节选）', author: '白居易', dynasty: '唐', cat: '田园', bg: 'summer', lines: ['田家少闲月', '五月人倍忙', '夜来南风起', '小麦覆陇黄'] },
  { emoji: '🎶', title: '闻官军收河南河北', author: '杜甫', dynasty: '唐', cat: '爱国', bg: 'spring', lines: ['剑外忽传收蓟北', '初闻涕泪满衣裳', '却看妻子愁何在', '漫卷诗书喜欲狂'] },
  { emoji: '🌅', title: '登高', author: '杜甫', dynasty: '唐', cat: '山水', bg: 'autumn', lines: ['风急天高猿啸哀', '渚清沙白鸟飞回', '无边落木萧萧下', '不尽长江滚滚来'] },
  { emoji: '🎭', title: '江南逢李龟年', author: '杜甫', dynasty: '唐', cat: '抒情', bg: 'spring', lines: ['岐王宅里寻常见', '崔九堂前几度闻', '正是江南好风景', '落花时节又逢君'] },
]
