export const animalQuestions = [
  { emoji: '🐶', english: 'Dog', chinese: '狗', options: ['Cat', 'Dog', 'Bird'] },
  { emoji: '🐱', english: 'Cat', chinese: '猫', options: ['Dog', 'Cat', 'Fish'] },
  { emoji: '🐟', english: 'Fish', chinese: '鱼', options: ['Fish', 'Bird', 'Frog'] },
  { emoji: '🐦', english: 'Bird', chinese: '鸟', options: ['Cat', 'Fish', 'Bird'] },
  { emoji: '🐰', english: 'Rabbit', chinese: '兔子', options: ['Rabbit', 'Dog', 'Cat'] },
  { emoji: '🐘', english: 'Elephant', chinese: '大象', options: ['Fish', 'Elephant', 'Bird'] },
  { emoji: '🦁', english: 'Lion', chinese: '狮子', options: ['Lion', 'Cat', 'Dog'] },
  { emoji: '🐵', english: 'Monkey', chinese: '猴子', options: ['Bird', 'Monkey', 'Fish'] },
  { emoji: '🐼', english: 'Panda', chinese: '熊猫', options: ['Panda', 'Rabbit', 'Dog'] },
  { emoji: '🐻', english: 'Bear', chinese: '熊', options: ['Cat', 'Bear', 'Lion'] },
  { emoji: '🦆', english: 'Duck', chinese: '鸭子', options: ['Bird', 'Fish', 'Duck'] },
  { emoji: '🐸', english: 'Frog', chinese: '青蛙', options: ['Frog', 'Rabbit', 'Bird'] },
  { emoji: '🐷', english: 'Pig', chinese: '猪', options: ['Dog', 'Pig', 'Cat'] },
  { emoji: '🐄', english: 'Cow', chinese: '牛', options: ['Cow', 'Duck', 'Pig'] },
  { emoji: '🐑', english: 'Sheep', chinese: '羊', options: ['Sheep', 'Cow', 'Dog'] },
  { emoji: '🐔', english: 'Chicken', chinese: '鸡', options: ['Duck', 'Chicken', 'Bird'] },
  { emoji: '🐴', english: 'Horse', chinese: '马', options: ['Cow', 'Horse', 'Donkey'] },
  { emoji: '🐍', english: 'Snake', chinese: '蛇', options: ['Snake', 'Fish', 'Worm'] },
  { emoji: '🐢', english: 'Turtle', chinese: '乌龟', options: ['Frog', 'Turtle', 'Snake'] },
  { emoji: '🐙', english: 'Octopus', chinese: '章鱼', options: ['Fish', 'Octopus', 'Crab'] },
  { emoji: '🦐', english: 'Shrimp', chinese: '虾', options: ['Shrimp', 'Fish', 'Crab'] },
  { emoji: '🦀', english: 'Crab', chinese: '螃蟹', options: ['Crab', 'Shrimp', 'Fish'] },
  { emoji: '🐳', english: 'Whale', chinese: '鲸鱼', options: ['Whale', 'Fish', 'Shark'] },
  { emoji: '🐬', english: 'Dolphin', chinese: '海豚', options: ['Dolphin', 'Whale', 'Fish'] },
  { emoji: '🦈', english: 'Shark', chinese: '鲨鱼', options: ['Whale', 'Shark', 'Fish'] },
  { emoji: '🐊', english: 'Crocodile', chinese: '鳄鱼', options: ['Crocodile', 'Snake', 'Lizard'] },
  { emoji: '🦎', english: 'Lizard', chinese: '蜥蜴', options: ['Lizard', 'Snake', 'Frog'] },
  { emoji: '🦉', english: 'Owl', chinese: '猫头鹰', options: ['Bird', 'Owl', 'Bat'] },
  { emoji: '🦅', english: 'Eagle', chinese: '老鹰', options: ['Bird', 'Eagle', 'Hawk'] },
  { emoji: '🦜', english: 'Parrot', chinese: '鹦鹉', options: ['Bird', 'Parrot', 'Duck'] },
  { emoji: '🦩', english: 'Flamingo', chinese: '火烈鸟', options: ['Bird', 'Flamingo', 'Stork'] },
  { emoji: '🦚', english: 'Peacock', chinese: '孔雀', options: ['Bird', 'Peacock', 'Chicken'] },
  { emoji: '🐧', english: 'Penguin', chinese: '企鹅', options: ['Penguin', 'Bird', 'Duck'] },
  { emoji: '🦇', english: 'Bat', chinese: '蝙蝠', options: ['Bird', 'Bat', 'Mouse'] },
  { emoji: '🐝', english: 'Bee', chinese: '蜜蜂', options: ['Bee', 'Fly', 'Ant'] },
  { emoji: '🐛', english: 'Bug', chinese: '虫子', options: ['Bug', 'Ant', 'Bee'] },
  { emoji: '🦋', english: 'Butterfly', chinese: '蝴蝶', options: ['Butterfly', 'Bee', 'Bird'] },
  { emoji: '🐌', english: 'Snail', chinese: '蜗牛', options: ['Snail', 'Bug', 'Worm'] },
  { emoji: '🐞', english: 'Ladybug', chinese: '瓢虫', options: ['Ladybug', 'Bee', 'Ant'] },
  { emoji: '🐜', english: 'Ant', chinese: '蚂蚁', options: ['Ant', 'Bee', 'Bug'] },
  { emoji: '🦟', english: 'Mosquito', chinese: '蚊子', options: ['Mosquito', 'Fly', 'Bee'] },
  { emoji: '🦗', english: 'Cricket', chinese: '蟋蟀', options: ['Cricket', 'Bug', 'Frog'] },
  { emoji: '🐭', english: 'Mouse', chinese: '老鼠', options: ['Mouse', 'Rat', 'Hamster'] },
  { emoji: '🐹', english: 'Hamster', chinese: '仓鼠', options: ['Hamster', 'Mouse', 'Rabbit'] },
  { emoji: '🐿️', english: 'Squirrel', chinese: '松鼠', options: ['Squirrel', 'Mouse', 'Rabbit'] },
  { emoji: '🦔', english: 'Hedgehog', chinese: '刺猬', options: ['Hedgehog', 'Mouse', 'Porcupine'] },
  { emoji: '🦊', english: 'Fox', chinese: '狐狸', options: ['Fox', 'Wolf', 'Dog'] },
  { emoji: '🐺', english: 'Wolf', chinese: '狼', options: ['Wolf', 'Fox', 'Dog'] },
  { emoji: '🦝', english: 'Raccoon', chinese: '浣熊', options: ['Raccoon', 'Fox', 'Bear'] },
  { emoji: '🐗', english: 'Boar', chinese: '野猪', options: ['Boar', 'Pig', 'Bear'] },
  { emoji: '🦌', english: 'Deer', chinese: '鹿', options: ['Deer', 'Horse', 'Cow'] },
  { emoji: '🐪', english: 'Camel', chinese: '骆驼', options: ['Camel', 'Horse', 'Donkey'] },
  { emoji: '🦒', english: 'Giraffe', chinese: '长颈鹿', options: ['Giraffe', 'Horse', 'Deer'] },
  { emoji: '🐃', english: 'Buffalo', chinese: '水牛', options: ['Buffalo', 'Cow', 'Ox'] },
  { emoji: '🦏', english: 'Rhinoceros', chinese: '犀牛', options: ['Rhinoceros', 'Hippo', 'Elephant'] },
  { emoji: '🦛', english: 'Hippopotamus', chinese: '河马', options: ['Hippopotamus', 'Rhinoceros', 'Elephant'] },
  { emoji: '🐆', english: 'Leopard', chinese: '豹子', options: ['Leopard', 'Cheetah', 'Tiger'] },
  { emoji: '🐅', english: 'Tiger', chinese: '老虎', options: ['Tiger', 'Lion', 'Leopard'] },
  { emoji: '🦍', english: 'Gorilla', chinese: '大猩猩', options: ['Gorilla', 'Monkey', 'Ape'] },
  { emoji: '🐒', english: 'Ape', chinese: '猿', options: ['Monkey', 'Ape', 'Gorilla'] },
  { emoji: '🦧', english: 'Orangutan', chinese: '猩猩', options: ['Orangutan', 'Monkey', 'Ape'] },
  { emoji: '🐩', english: 'Poodle', chinese: '贵宾犬', options: ['Poodle', 'Dog', 'Puppy'] },
  { emoji: '🐕', english: 'Puppy', chinese: '小狗', options: ['Puppy', 'Dog', 'Kitten'] },
  { emoji: '🐈', english: 'Kitten', chinese: '小猫', options: ['Kitten', 'Cat', 'Puppy'] },
  { emoji: '🦮', english: 'Guide Dog', chinese: '导盲犬', options: ['Guide Dog', 'Dog', 'Puppy'] },
  { emoji: '🐕‍🦺', english: 'Service Dog', chinese: '服务犬', options: ['Service Dog', 'Dog', 'Guide Dog'] },
  { emoji: '🦙', english: 'Llama', chinese: '羊驼', options: ['Llama', 'Camel', 'Sheep'] },
  { emoji: '🦘', english: 'Kangaroo', chinese: '袋鼠', options: ['Kangaroo', 'Rabbit', 'Deer'] },
  { emoji: '🦡', english: 'Badger', chinese: '獾', options: ['Badger', 'Bear', 'Raccoon'] },
  { emoji: '🦨', english: 'Skunk', chinese: '臭鼬', options: ['Skunk', 'Badger', 'Raccoon'] },
  { emoji: '🦫', english: 'Beaver', chinese: '海狸', options: ['Beaver', 'Otter', 'Muskrat'] },
  { emoji: '🦦', english: 'Otter', chinese: '水獭', options: ['Otter', 'Beaver', 'Seal'] },
  { emoji: '🦭', english: 'Seal', chinese: '海豹', options: ['Seal', 'Otter', 'Walrus'] },
  { emoji: '🦆', english: 'Goose', chinese: '鹅', options: ['Goose', 'Duck', 'Swan'] },
  { emoji: '🦢', english: 'Swan', chinese: '天鹅', options: ['Swan', 'Duck', 'Goose'] },
  { emoji: '🦃', english: 'Turkey', chinese: '火鸡', options: ['Turkey', 'Chicken', 'Peacock'] },
  { emoji: '🐓', english: 'Rooster', chinese: '公鸡', options: ['Rooster', 'Chicken', 'Hen'] },
  { emoji: '🐣', english: 'Chick', chinese: '小鸡', options: ['Chick', 'Chicken', 'Duckling'] },
  { emoji: '🐤', english: 'Duckling', chinese: '小鸭', options: ['Duckling', 'Chick', 'Duck'] },
  { emoji: '🐦‍⬛', english: 'Crow', chinese: '乌鸦', options: ['Crow', 'Bird', 'Raven'] },
  { emoji: '🕊️', english: 'Dove', chinese: '鸽子', options: ['Dove', 'Bird', 'Pigeon'] },
  { emoji: '🦅', english: 'Hawk', chinese: '鹰', options: ['Hawk', 'Eagle', 'Falcon'] },
  { emoji: '🦉', english: 'Barn Owl', chinese: '仓鸮', options: ['Barn Owl', 'Owl', 'Bird'] },
  { emoji: '🐸', english: 'Toad', chinese: '蟾蜍', options: ['Toad', 'Frog', 'Salamander'] },
  { emoji: '🦎', english: 'Gecko', chinese: '壁虎', options: ['Gecko', 'Lizard', 'Salamander'] },
  { emoji: '🐍', english: 'Python', chinese: '蟒蛇', options: ['Python', 'Snake', 'Boa'] },
  { emoji: '🐢', english: 'Tortoise', chinese: '陆龟', options: ['Tortoise', 'Turtle', 'Snail'] },
  { emoji: '🦕', english: 'Brachiosaurus', chinese: '腕龙', options: ['Brachiosaurus', 'Dinosaur', 'Diplodocus'] },
  { emoji: '🦖', english: 'T-Rex', chinese: '霸王龙', options: ['T-Rex', 'Dinosaur', 'Velociraptor'] },
  { emoji: '🐉', english: 'Dragon', chinese: '龙', options: ['Dragon', 'Dinosaur', 'Lizard'] },
  { emoji: '🦋', english: 'Moth', chinese: '飞蛾', options: ['Moth', 'Butterfly', 'Bee'] },
  { emoji: '🐛', english: 'Caterpillar', chinese: '毛毛虫', options: ['Caterpillar', 'Bug', 'Worm'] },
  { emoji: '🪱', english: 'Worm', chinese: '蚯蚓', options: ['Worm', 'Snake', 'Bug'] },
  { emoji: '🐜', english: 'Termite', chinese: '白蚁', options: ['Termite', 'Ant', 'Bug'] },
  { emoji: '🪲', english: 'Beetle', chinese: '甲虫', options: ['Beetle', 'Bug', 'Ladybug'] },
  { emoji: '🪳', english: 'Cockroach', chinese: '蟑螂', options: ['Cockroach', 'Bug', 'Beetle'] },
  { emoji: '🦂', english: 'Scorpion', chinese: '蝎子', options: ['Scorpion', 'Spider', 'Crab'] },
  { emoji: '🕷️', english: 'Spider', chinese: '蜘蛛', options: ['Spider', 'Scorpion', 'Ant'] },
  { emoji: '🕸️', english: 'Web', chinese: '蛛网', options: ['Web', 'Spider', 'Cocoon'] },
  { emoji: '🐚', english: 'Shell', chinese: '贝壳', options: ['Shell', 'Snail', 'Crab'] },
  { emoji: '🐠', english: 'Tropical Fish', chinese: '热带鱼', options: ['Tropical Fish', 'Fish', 'Goldfish'] },
  { emoji: '🐡', english: 'Pufferfish', chinese: '河豚', options: ['Pufferfish', 'Fish', 'Blowfish'] },
  { emoji: '🐋', english: 'Blue Whale', chinese: '蓝鲸', options: ['Blue Whale', 'Whale', 'Fish'] },
  { emoji: '🦭', english: 'Walrus', chinese: '海象', options: ['Walrus', 'Seal', 'Sea Lion'] },
  { emoji: '🐬', english: 'Porpoise', chinese: '鼠海豚', options: ['Porpoise', 'Dolphin', 'Whale'] },
  { emoji: '🦈', english: 'Hammerhead', chinese: '锤头鲨', options: ['Hammerhead', 'Shark', 'Fish'] },
  { emoji: '🐟', english: 'Salmon', chinese: '三文鱼', options: ['Salmon', 'Fish', 'Trout'] },
  { emoji: '🐟', english: 'Goldfish', chinese: '金鱼', options: ['Goldfish', 'Fish', 'Koi'] },
  { emoji: '🦐', english: 'Lobster', chinese: '龙虾', options: ['Lobster', 'Shrimp', 'Crab'] },
  { emoji: '🦞', english: 'Crayfish', chinese: '小龙虾', options: ['Crayfish', 'Lobster', 'Shrimp'] },
  { emoji: '🦑', english: 'Squid', chinese: '鱿鱼', options: ['Squid', 'Octopus', 'Cuttlefish'] },
  { emoji: '🐙', english: 'Cuttlefish', chinese: '墨鱼', options: ['Cuttlefish', 'Octopus', 'Squid'] },
  { emoji: '🪸', english: 'Coral', chinese: '珊瑚', options: ['Coral', 'Shell', 'Anemone'] },
  { emoji: '🐌', english: 'Slug', chinese: '蛞蝓', options: ['Slug', 'Snail', 'Worm'] },
  { emoji: '🦠', english: 'Amoeba', chinese: '变形虫', options: ['Amoeba', 'Bug', 'Germ'] },
  { emoji: '🦮', english: 'Sheepdog', chinese: '牧羊犬', options: ['Sheepdog', 'Dog', 'Wolf'] },
  { emoji: '🐕', english: 'Husky', chinese: '哈士奇', options: ['Husky', 'Dog', 'Wolf'] },
  { emoji: '🐩', english: 'Pomeranian', chinese: '博美', options: ['Pomeranian', 'Dog', 'Poodle'] },
  { emoji: '🐈', english: 'Persian Cat', chinese: '波斯猫', options: ['Persian Cat', 'Cat', 'Kitten'] },
  { emoji: '🐇', english: 'Bunny', chinese: '小兔', options: ['Bunny', 'Rabbit', 'Hare'] },
  { emoji: '🦌', english: 'Moose', chinese: '驼鹿', options: ['Moose', 'Deer', 'Elk'] },
  { emoji: '🐐', english: 'Goat', chinese: '山羊', options: ['Goat', 'Sheep', 'Ram'] },
  { emoji: '🐏', english: 'Ram', chinese: '公羊', options: ['Ram', 'Sheep', 'Goat'] },
  { emoji: '🐑', english: 'Lamb', chinese: '小羊', options: ['Lamb', 'Sheep', 'Goat'] },
  { emoji: '🐖', english: 'Sow', chinese: '母猪', options: ['Sow', 'Pig', 'Boar'] },
  { emoji: '🐎', english: 'Pony', chinese: '小马', options: ['Pony', 'Horse', 'Donkey'] },
  { emoji: '🫏', english: 'Donkey', chinese: '驴', options: ['Donkey', 'Horse', 'Mule'] },
  { emoji: '🐫', english: 'Dromedary', chinese: '单峰驼', options: ['Dromedary', 'Camel', 'Llama'] },
  { emoji: '🦣', english: 'Mammoth', chinese: '猛犸象', options: ['Mammoth', 'Elephant', 'Walrus'] },
  { emoji: '🦜', english: 'Macaw', chinese: '金刚鹦鹉', options: ['Macaw', 'Parrot', 'Bird'] },
  { emoji: '🦩', english: 'Stork', chinese: '鹳', options: ['Stork', 'Flamingo', 'Crane'] },
  { emoji: '🐦', english: 'Hummingbird', chinese: '蜂鸟', options: ['Hummingbird', 'Bird', 'Bee'] },
  { emoji: '🦤', english: 'Dodo', chinese: '渡渡鸟', options: ['Dodo', 'Bird', 'Ostrich'] },
  { emoji: '🦩', english: 'Crane', chinese: '鹤', options: ['Crane', 'Stork', 'Flamingo'] },
  { emoji: '🦅', english: 'Falcon', chinese: '猎鹰', options: ['Falcon', 'Hawk', 'Eagle'] },
  { emoji: '🐦‍⬛', english: 'Raven', chinese: '渡鸦', options: ['Raven', 'Crow', 'Bird'] },
  { emoji: '🐧', english: 'King Penguin', chinese: '王企鹅', options: ['King Penguin', 'Penguin', 'Bird'] },
  { emoji: '🦉', english: 'Screech Owl', chinese: '鸣角鸮', options: ['Screech Owl', 'Owl', 'Bird'] },
  { emoji: '🦎', english: 'Chameleon', chinese: '变色龙', options: ['Chameleon', 'Lizard', 'Gecko'] },
  { emoji: '🐍', english: 'Cobra', chinese: '眼镜蛇', options: ['Cobra', 'Snake', 'Python'] },
  { emoji: '🐢', english: 'Sea Turtle', chinese: '海龟', options: ['Sea Turtle', 'Turtle', 'Tortoise'] },
  { emoji: '🐸', english: 'Tree Frog', chinese: '树蛙', options: ['Tree Frog', 'Frog', 'Toad'] },
  { emoji: '🦋', english: 'Monarch', chinese: '帝王蝶', options: ['Monarch', 'Butterfly', 'Moth'] },
]

export const fruitQuestions = [
  { emoji: '🍎', english: 'Apple', chinese: '苹果', options: ['Apple', 'Orange', 'Pear'] },
  { emoji: '🍌', english: 'Banana', chinese: '香蕉', options: ['Grape', 'Banana', 'Apple'] },
  { emoji: '🍊', english: 'Orange', chinese: '橙子', options: ['Orange', 'Lemon', 'Peach'] },
  { emoji: '🍇', english: 'Grape', chinese: '葡萄', options: ['Kiwi', 'Grape', 'Cherry'] },
  { emoji: '🍉', english: 'Watermelon', chinese: '西瓜', options: ['Watermelon', 'Apple', 'Banana'] },
  { emoji: '🍓', english: 'Strawberry', chinese: '草莓', options: ['Cherry', 'Strawberry', 'Grape'] },
  { emoji: '🍐', english: 'Pear', chinese: '梨', options: ['Apple', 'Pear', 'Mango'] },
  { emoji: '🍑', english: 'Peach', chinese: '桃子', options: ['Peach', 'Orange', 'Banana'] },
  { emoji: '🍒', english: 'Cherry', chinese: '樱桃', options: ['Grape', 'Cherry', 'Strawberry'] },
  { emoji: '🍋', english: 'Lemon', chinese: '柠檬', options: ['Lemon', 'Orange', 'Apple'] },
  { emoji: '🥭', english: 'Mango', chinese: '芒果', options: ['Banana', 'Mango', 'Pear'] },
  { emoji: '🥝', english: 'Kiwi', chinese: '猕猴桃', options: ['Kiwi', 'Grape', 'Lemon'] },
]

export const vehicleQuestions = [
  { emoji: '🚗', english: 'Car', chinese: '小汽车', options: ['Bus', 'Car', 'Bike'] },
  { emoji: '🚌', english: 'Bus', chinese: '公共汽车', options: ['Bus', 'Train', 'Car'] },
  { emoji: '🚲', english: 'Bike', chinese: '自行车', options: ['Car', 'Bike', 'Boat'] },
  { emoji: '✈️', english: 'Plane', chinese: '飞机', options: ['Helicopter', 'Plane', 'Train'] },
  { emoji: '🚂', english: 'Train', chinese: '火车', options: ['Train', 'Bus', 'Taxi'] },
  { emoji: '⛵', english: 'Boat', chinese: '小船', options: ['Ship', 'Boat', 'Car'] },
  { emoji: '🚚', english: 'Truck', chinese: '卡车', options: ['Truck', 'Bus', 'Car'] },
  { emoji: '🚁', english: 'Helicopter', chinese: '直升机', options: ['Plane', 'Helicopter', 'Boat'] },
  { emoji: '🚕', english: 'Taxi', chinese: '出租车', options: ['Bus', 'Taxi', 'Truck'] },
  { emoji: '🚀', english: 'Rocket', chinese: '火箭', options: ['Rocket', 'Plane', 'Train'] },
]

export const bodyQuestions = [
  { emoji: '👤', english: 'Head', chinese: '头', options: ['Head', 'Hand', 'Foot'] },
  { emoji: '👁️', english: 'Eye', chinese: '眼睛', options: ['Ear', 'Eye', 'Nose'] },
  { emoji: '👃', english: 'Nose', chinese: '鼻子', options: ['Mouth', 'Nose', 'Eye'] },
  { emoji: '👄', english: 'Mouth', chinese: '嘴巴', options: ['Mouth', 'Head', 'Ear'] },
  { emoji: '👂', english: 'Ear', chinese: '耳朵', options: ['Eye', 'Ear', 'Finger'] },
  { emoji: '✋', english: 'Hand', chinese: '手', options: ['Foot', 'Hand', 'Arm'] },
  { emoji: '🦶', english: 'Foot', chinese: '脚', options: ['Foot', 'Hand', 'Leg'] },
  { emoji: '💪', english: 'Arm', chinese: '手臂', options: ['Arm', 'Leg', 'Hand'] },
  { emoji: '🦵', english: 'Leg', chinese: '腿', options: ['Arm', 'Leg', 'Foot'] },
  { emoji: '☝️', english: 'Finger', chinese: '手指', options: ['Finger', 'Hand', 'Foot'] },
]

export const phraseQuestions = [
  { emoji: '👋', english: 'Hello!', chinese: '你好！', situation: '打招呼' },
  { emoji: '👋', english: 'Goodbye!', chinese: '再见！', situation: '告别' },
  { emoji: '🌅', english: 'Good morning!', chinese: '早上好！', situation: '早晨问候' },
  { emoji: '🌇', english: 'Good evening!', chinese: '晚上好！', situation: '晚间问候' },
  { emoji: '🌙', english: 'Good night!', chinese: '晚安！', situation: '睡前' },
  { emoji: '🙏', english: 'Thank you!', chinese: '谢谢你！', situation: '感谢' },
  { emoji: '😊', english: 'You are welcome!', chinese: '不客气！', situation: '回应感谢' },
  { emoji: '🙇', english: 'I am sorry!', chinese: '对不起！', situation: '道歉' },
  { emoji: '👍', english: 'Good job!', chinese: '做得好！', situation: '鼓励' },
  { emoji: '💪', english: 'You can do it!', chinese: '你能行！', situation: '鼓励' },
  { emoji: '❓', english: 'What is your name?', chinese: '你叫什么名字？', situation: '询问姓名' },
  { emoji: '📛', english: 'My name is...', chinese: '我叫……', situation: '介绍自己' },
  { emoji: '🎂', english: 'How old are you?', chinese: '你几岁了？', situation: '询问年龄' },
  { emoji: '💖', english: 'I love you!', chinese: '我爱你！', situation: '表达爱意' },
  { emoji: '🤝', english: 'Nice to meet you!', chinese: '很高兴认识你！', situation: '初次见面' },
  { emoji: '🍽️', english: 'I am hungry.', chinese: '我饿了。', situation: '表达需求' },
  { emoji: '💧', english: 'I am thirsty.', chinese: '我渴了。', situation: '表达需求' },
  { emoji: '😴', english: 'I am tired.', chinese: '我累了。', situation: '表达感受' },
  { emoji: '😄', english: 'I am happy!', chinese: '我很开心！', situation: '表达感受' },
  { emoji: '😢', english: 'I am sad.', chinese: '我很难过。', situation: '表达感受' },
  { emoji: '🚽', english: 'May I go to the bathroom?', chinese: '我可以去洗手间吗？', situation: '请求' },
  { emoji: '🤒', english: 'I don\'t feel well.', chinese: '我不舒服。', situation: '表达不适' },
  { emoji: '🎉', english: 'Happy birthday!', chinese: '生日快乐！', situation: '祝福' },
  { emoji: '🎄', english: 'Merry Christmas!', chinese: '圣诞快乐！', situation: '节日祝福' },
  { emoji: '🧨', english: 'Happy New Year!', chinese: '新年快乐！', situation: '节日祝福' },
  { emoji: '🍬', english: 'Trick or treat!', chinese: '不给糖就捣蛋！', situation: '万圣节' },
  { emoji: '👋', english: 'Hi!', chinese: '嗨！', situation: '打招呼' },
  { emoji: '🤗', english: 'How are you?', chinese: '你好吗？', situation: '打招呼' },
  { emoji: '🙂', english: 'I\'m fine, thank you.', chinese: '我很好，谢谢。', situation: '打招呼' },
  { emoji: '🎉', english: 'How\'s it going?', chinese: '最近怎么样？', situation: '打招呼' },
  { emoji: '👋', english: 'See you later!', chinese: '回头见！', situation: '告别' },
  { emoji: '👋', english: 'See you tomorrow!', chinese: '明天见！', situation: '告别' },
  { emoji: '🖐️', english: 'Bye bye!', chinese: '拜拜！', situation: '告别' },
  { emoji: '📞', english: 'Talk to you later!', chinese: '回头聊！', situation: '告别' },
  { emoji: '🌊', english: 'Have a nice day!', chinese: '祝你有美好的一天！', situation: '告别' },
  { emoji: '🙏', english: 'Thanks a lot!', chinese: '多谢！', situation: '感谢' },
  { emoji: '🥰', english: 'Thank you very much!', chinese: '非常感谢你！', situation: '感谢' },
  { emoji: '🎁', english: 'Thank you for your help!', chinese: '谢谢你的帮助！', situation: '感谢' },
  { emoji: '💖', english: 'I really appreciate it!', chinese: '我真的很感激！', situation: '感谢' },
  { emoji: '😅', english: 'Sorry!', chinese: '抱歉！', situation: '道歉' },
  { emoji: '🫂', english: 'It\'s okay.', chinese: '没关系。', situation: '回应道歉' },
  { emoji: '🙇', english: 'Please forgive me.', chinese: '请原谅我。', situation: '道歉' },
  { emoji: '🤷', english: 'That\'s all right.', chinese: '没关系。', situation: '回应道歉' },
  { emoji: '🙋', english: 'May I come in?', chinese: '我可以进来吗？', situation: '请求' },
  { emoji: '🤲', english: 'Please help me.', chinese: '请帮助我。', situation: '请求' },
  { emoji: '✋', english: 'May I ask a question?', chinese: '我可以问个问题吗？', situation: '请求' },
  { emoji: '🔄', english: 'Could you say it again?', chinese: '你能再说一遍吗？', situation: '请求' },
  { emoji: '🪑', english: 'Please sit down.', chinese: '请坐下。', situation: '请求' },
  { emoji: '😡', english: 'I am angry.', chinese: '我生气了。', situation: '表达感受' },
  { emoji: '😨', english: 'I am scared.', chinese: '我害怕。', situation: '表达感受' },
  { emoji: '🤩', english: 'I am excited!', chinese: '我很兴奋！', situation: '表达感受' },
  { emoji: '🥱', english: 'I am bored.', chinese: '我很无聊。', situation: '表达感受' },
  { emoji: '😲', english: 'I am surprised!', chinese: '我很惊讶！', situation: '表达感受' },
  { emoji: '😌', english: 'I am calm.', chinese: '我很平静。', situation: '表达感受' },
  { emoji: '🤔', english: 'I am confused.', chinese: '我很困惑。', situation: '表达感受' },
  { emoji: '😰', english: 'I am worried.', chinese: '我很担心。', situation: '表达感受' },
  { emoji: '📚', english: 'I like to read.', chinese: '我喜欢读书。', situation: '学校' },
  { emoji: '✏️', english: 'Let\'s draw!', chinese: '我们来画画！', situation: '学校' },
  { emoji: '📝', english: 'Do you have homework?', chinese: '你有作业吗？', situation: '学校' },
  { emoji: '📖', english: 'I read a book.', chinese: '我读书。', situation: '学校' },
  { emoji: '🖍️', english: 'I color a picture.', chinese: '我给画涂色。', situation: '学校' },
  { emoji: '🎒', english: 'I go to school.', chinese: '我去上学。', situation: '学校' },
  { emoji: '🔢', english: 'Let\'s count numbers!', chinese: '我们来数数！', situation: '学校' },
  { emoji: '🎵', english: 'Let\'s sing a song!', chinese: '我们来唱首歌！', situation: '学校' },
  { emoji: '🧪', english: 'Let\'s do science!', chinese: '我们来做实验！', situation: '学校' },
  { emoji: '✂️', english: 'Let\'s make a craft!', chinese: '我们来做个手工！', situation: '学校' },
  { emoji: '👩', english: 'This is my mom.', chinese: '这是我妈妈。', situation: '家庭' },
  { emoji: '👨', english: 'This is my dad.', chinese: '这是我爸爸。', situation: '家庭' },
  { emoji: '👧', english: 'This is my sister.', chinese: '这是我姐姐/妹妹。', situation: '家庭' },
  { emoji: '👦', english: 'This is my brother.', chinese: '这是我哥哥/弟弟。', situation: '家庭' },
  { emoji: '👴', english: 'I love my grandpa.', chinese: '我爱我爷爷。', situation: '家庭' },
  { emoji: '👵', english: 'I love my grandma.', chinese: '我爱我奶奶。', situation: '家庭' },
  { emoji: '👶', english: 'There is a baby.', chinese: '有一个宝宝。', situation: '家庭' },
  { emoji: '🐈', english: 'I have a pet cat.', chinese: '我有一只宠物猫。', situation: '家庭' },
  { emoji: '🏡', english: 'This is my home.', chinese: '这是我的家。', situation: '家庭' },
  { emoji: '🥛', english: 'I drink milk.', chinese: '我喝牛奶。', situation: '食物' },
  { emoji: '🥚', english: 'I like eggs.', chinese: '我喜欢鸡蛋。', situation: '食物' },
  { emoji: '🍞', english: 'I eat bread.', chinese: '我吃面包。', situation: '食物' },
  { emoji: '🍚', english: 'I eat rice.', chinese: '我吃米饭。', situation: '食物' },
  { emoji: '🥕', english: 'I like carrots.', chinese: '我喜欢胡萝卜。', situation: '食物' },
  { emoji: '🍎', english: 'I eat an apple.', chinese: '我吃苹果。', situation: '食物' },
  { emoji: '🍪', english: 'I like cookies!', chinese: '我喜欢饼干！', situation: '食物' },
  { emoji: '🍦', english: 'I want ice cream!', chinese: '我想要冰淇淋！', situation: '食物' },
  { emoji: '🍕', english: 'I want pizza!', chinese: '我想要披萨！', situation: '食物' },
  { emoji: '🍬', english: 'Candy is sweet!', chinese: '糖果很甜！', situation: '食物' },
  { emoji: '🥤', english: 'Can I have some water?', chinese: '我能喝点水吗？', situation: '食物' },
  { emoji: '☀️', english: 'It is sunny.', chinese: '天气晴朗。', situation: '天气' },
  { emoji: '☁️', english: 'It is cloudy.', chinese: '天气多云。', situation: '天气' },
  { emoji: '🌧️', english: 'It is raining.', chinese: '下雨了。', situation: '天气' },
  { emoji: '❄️', english: 'It is snowing.', chinese: '下雪了。', situation: '天气' },
  { emoji: '🌬️', english: 'It is windy.', chinese: '刮风了。', situation: '天气' },
  { emoji: '🌡️', english: 'It is hot today.', chinese: '今天很热。', situation: '天气' },
  { emoji: '🥶', english: 'It is cold outside.', chinese: '外面很冷。', situation: '天气' },
  { emoji: '🌈', english: 'Look at the rainbow!', chinese: '看彩虹！', situation: '天气' },
  { emoji: '🔴', english: 'I like the color red.', chinese: '我喜欢红色。', situation: '颜色' },
  { emoji: '🔵', english: 'I like the color blue.', chinese: '我喜欢蓝色。', situation: '颜色' },
  { emoji: '🟢', english: 'I like the color green.', chinese: '我喜欢绿色。', situation: '颜色' },
  { emoji: '🟡', english: 'I like the color yellow.', chinese: '我喜欢黄色。', situation: '颜色' },
  { emoji: '🟣', english: 'I like the color purple.', chinese: '我喜欢紫色。', situation: '颜色' },
  { emoji: '🩷', english: 'I like the color pink.', chinese: '我喜欢粉色。', situation: '颜色' },
  { emoji: '1️⃣', english: 'One', chinese: '一', situation: '数字' },
  { emoji: '2️⃣', english: 'Two', chinese: '二', situation: '数字' },
  { emoji: '3️⃣', english: 'Three', chinese: '三', situation: '数字' },
  { emoji: '4️⃣', english: 'Four', chinese: '四', situation: '数字' },
  { emoji: '5️⃣', english: 'Five', chinese: '五', situation: '数字' },
  { emoji: '⏰', english: 'Time to wake up!', chinese: '该起床了！', situation: '时间' },
  { emoji: '🍳', english: 'Time to eat breakfast!', chinese: '该吃早餐了！', situation: '时间' },
  { emoji: '🛏️', english: 'Time to go to bed!', chinese: '该上床睡觉了！', situation: '时间' },
  { emoji: '🎮', english: 'Time to play outside!', chinese: '该出去玩啦！', situation: '时间' },
  { emoji: '🧹', english: 'Time to clean up!', chinese: '该收拾整理了！', situation: '时间' },
  { emoji: '🦆', english: 'The duck says quack.', chinese: '鸭子嘎嘎叫。', situation: '动物' },
  { emoji: '🐱', english: 'The cat says meow.', chinese: '猫喵喵叫。', situation: '动物' },
  { emoji: '🐶', english: 'The dog says woof.', chinese: '狗汪汪叫。', situation: '动物' },
  { emoji: '🐄', english: 'The cow says moo.', chinese: '牛哞哞叫。', situation: '动物' },
  { emoji: '🐑', english: 'The sheep says baa.', chinese: '羊咩咩叫。', situation: '动物' },
  { emoji: '⚽', english: 'Let\'s play soccer!', chinese: '我们来踢足球！', situation: '游戏' },
  { emoji: '🧩', english: 'Let\'s do a puzzle!', chinese: '我们来拼拼图！', situation: '游戏' },
  { emoji: '🪁', english: 'Let\'s fly a kite!', chinese: '我们来放风筝！', situation: '游戏' },
  { emoji: '🏃', english: 'Let\'s race!', chinese: '我们来赛跑！', situation: '游戏' },
  { emoji: '🤸', english: 'Let\'s jump rope!', chinese: '我们来跳绳！', situation: '游戏' },
  { emoji: '💃', english: 'Let\'s dance together!', chinese: '我们一起跳舞！', situation: '游戏' },
  { emoji: '🤲', english: 'Please', chinese: '请', situation: '礼貌' },
  { emoji: '🫂', english: 'Excuse me', chinese: '打扰一下', situation: '礼貌' },
  { emoji: '😇', english: 'Bless you!', chinese: '保佑你！', situation: '礼貌' },
  { emoji: '🚪', english: 'After you', chinese: '您先请', situation: '礼貌' },
  { emoji: '💐', english: 'You\'re so kind!', chinese: '你真好！', situation: '礼貌' },
  { emoji: '🐰', english: 'Happy Easter!', chinese: '复活节快乐！', situation: '节日' },
  { emoji: '💖', english: 'Happy Valentine\'s Day!', chinese: '情人节快乐！', situation: '节日' },
  { emoji: '🦃', english: 'Happy Thanksgiving!', chinese: '感恩节快乐！', situation: '节日' },
  { emoji: '🎃', english: 'Happy Halloween!', chinese: '万圣节快乐！', situation: '节日' },
  { emoji: '🏮', english: 'Happy Lantern Festival!', chinese: '元宵节快乐！', situation: '节日' },
  { emoji: '🥟', english: 'Happy Dragon Boat Festival!', chinese: '端午节快乐！', situation: '节日' },
  { emoji: '🪥', english: 'Brush your teeth.', chinese: '刷牙。', situation: '健康' },
  { emoji: '🧼', english: 'Wash your hands.', chinese: '洗手。', situation: '健康' },
  { emoji: '🛁', english: 'Take a bath.', chinese: '洗澡。', situation: '健康' },
  { emoji: '🏃', english: 'Exercise every day!', chinese: '每天运动！', situation: '健康' },
  { emoji: '🥦', english: 'Eat your vegetables!', chinese: '吃蔬菜！', situation: '健康' },
  { emoji: '💤', english: 'Have a good sleep.', chinese: '睡个好觉。', situation: '健康' },
  { emoji: '🎨', english: 'I like painting.', chinese: '我喜欢画画。', situation: '爱好' },
  { emoji: '🎤', english: 'I like singing.', chinese: '我喜欢唱歌。', situation: '爱好' },
  { emoji: '📚', english: 'I like reading books.', chinese: '我喜欢读书。', situation: '爱好' },
  { emoji: '🌸', english: 'I like planting flowers.', chinese: '我喜欢种花。', situation: '爱好' },
  { emoji: '🏊', english: 'I like swimming.', chinese: '我喜欢游泳。', situation: '爱好' },
  { emoji: '🧳', english: 'Let\'s go on a trip!', chinese: '我们去旅行吧！', situation: '旅行' },
  { emoji: '🏖️', english: 'Let\'s go to the beach!', chinese: '我们去海滩吧！', situation: '旅行' },
  { emoji: '🏔️', english: 'Let\'s climb a mountain!', chinese: '我们去爬山吧！', situation: '旅行' },
  { emoji: '🏰', english: 'Let\'s go to the park!', chinese: '我们去公园吧！', situation: '旅行' },
  { emoji: '🚌', english: 'Let\'s take a bus!', chinese: '我们坐公交车吧！', situation: '旅行' },
  { emoji: '🌟', english: 'You are special!', chinese: '你很特别！', situation: '鼓励' },
  { emoji: '🎈', english: 'Have a wonderful day!', chinese: '祝你有美好的一天！', situation: '祝福' },
]

export { songQuestions } from './songsData.js'

export const colorQuestions = [
  { color: '#FF4757', english: 'Red', chinese: '红色' },
  { color: '#2ED573', english: 'Green', chinese: '绿色' },
  { color: '#1E90FF', english: 'Blue', chinese: '蓝色' },
  { color: '#FFA502', english: 'Orange', chinese: '橙色' },
  { color: '#FFD93D', english: 'Yellow', chinese: '黄色' },
  { color: '#A78BFA', english: 'Purple', chinese: '紫色' },
  { color: '#FF6B9D', english: 'Pink', chinese: '粉色' },
  { color: '#2C3E50', english: 'Black', chinese: '黑色' },
  { color: '#FFFFFF', english: 'White', chinese: '白色' },
  { color: '#8B4513', english: 'Brown', chinese: '棕色' },
  { color: '#95A5A6', english: 'Gray', chinese: '灰色' },
  { color: '#FFD700', english: 'Gold', chinese: '金色' },
]

export const comparePairs = [
  { big: '🐘', bigL: '大象', small: '🐭', smallL: '老鼠' },
  { big: '🚗', bigL: '汽车', small: '🚲', smallL: '自行车' },
  { big: '🏠', bigL: '房子', small: '⛺', smallL: '帐篷' },
  { big: '🌳', bigL: '大树', small: '🌷', smallL: '小花' },
  { big: '🐋', bigL: '鲸鱼', small: '🐟', smallL: '小鱼' },
  { big: '🦒', bigL: '长颈鹿', small: '🐰', smallL: '兔子' },
  { big: '🌞', bigL: '太阳', small: '🌙', smallL: '月亮' },
  { big: '🏔️', bigL: '大山', small: '🪨', smallL: '石头' },
  { big: '🦅', bigL: '老鹰', small: '🐦', smallL: '小鸟' },
  { big: '🐉', bigL: '恐龙', small: '🦎', smallL: '蜥蜴' },
  { big: '🍉', bigL: '西瓜', small: '🍇', smallL: '葡萄' },
  { big: '🌊', bigL: '大海', small: '💧', smallL: '水滴' },
]
