export const animalQuestions = [
  { emoji: '🐶', english: 'Dog', chinese: '狗', options: ['Cat', 'Dog', 'Bird'] },
  { emoji: '🐱', english: 'Cat', chinese: '猫', options: ['Dog', 'Cat', 'Fish'] },
  { emoji: '🐟', english: 'Fish', chinese: '鱼', options: ['Fish', 'Bird', 'Frog'] },
  { emoji: '🐦', english: 'Bird', chinese: '鸟', options: ['Cat', 'Fish', 'Bird'] },
  { emoji: '🐰', english: 'Rabbit', chinese: '兔子', options: ['Rabbit', 'Dog', 'Cat'] },
  { emoji: '🐘', english: 'Elephant', chinese: '大象', options: ['Fish', 'Elephant', 'Bird'] },
  { emoji: '🦁', english: 'Lion', chinese: '狮子', options: ['Lion', 'Cat', 'Dog'] },
  { emoji: '🐵', english: 'Monkey', chinese: '猴子', options: ['Bird', 'Monkey', 'Fish'] },
  { emoji: '🐼', english: 'Panda', chinese: '熊猫', options: ['Panda', 'Rabbit', 'Dog'] },
  { emoji: '🐻', english: 'Bear', chinese: '熊', options: ['Cat', 'Bear', 'Lion'] },
  { emoji: '🦆', english: 'Duck', chinese: '鸭子', options: ['Bird', 'Fish', 'Duck'] },
  { emoji: '🐸', english: 'Frog', chinese: '青蛙', options: ['Frog', 'Rabbit', 'Bird'] },
  { emoji: '🐷', english: 'Pig', chinese: '猪', options: ['Dog', 'Pig', 'Cat'] },
  { emoji: '🐄', english: 'Cow', chinese: '牛', options: ['Cow', 'Duck', 'Pig'] },
  { emoji: '🐑', english: 'Sheep', chinese: '羊', options: ['Sheep', 'Cow', 'Dog'] },
  { emoji: '🐔', english: 'Chicken', chinese: '鸡', options: ['Duck', 'Chicken', 'Bird'] },
  { emoji: '🐴', english: 'Horse', chinese: '马', options: ['Cow', 'Horse', 'Donkey'] },
  { emoji: '🐍', english: 'Snake', chinese: '蛇', options: ['Snake', 'Fish', 'Worm'] },
  { emoji: '🐢', english: 'Turtle', chinese: '乌龟', options: ['Frog', 'Turtle', 'Snake'] },
  { emoji: '🐙', english: 'Octopus', chinese: '章鱼', options: ['Fish', 'Octopus', 'Crab'] },
  { emoji: '🦐', english: 'Shrimp', chinese: '虾', options: ['Shrimp', 'Fish', 'Crab'] },
  { emoji: '🦀', english: 'Crab', chinese: '螃蟹', options: ['Crab', 'Shrimp', 'Fish'] },
  { emoji: '🐳', english: 'Whale', chinese: '鲸鱼', options: ['Whale', 'Fish', 'Shark'] },
  { emoji: '🐬', english: 'Dolphin', chinese: '海豚', options: ['Dolphin', 'Whale', 'Fish'] },
  { emoji: '🦈', english: 'Shark', chinese: '鲨鱼', options: ['Whale', 'Shark', 'Fish'] },
  { emoji: '🐊', english: 'Crocodile', chinese: '鳄鱼', options: ['Crocodile', 'Snake', 'Lizard'] },
  { emoji: '🦎', english: 'Lizard', chinese: '蜥蜴', options: ['Lizard', 'Snake', 'Frog'] },
  { emoji: '🦉', english: 'Owl', chinese: '猫头鹰', options: ['Bird', 'Owl', 'Bat'] },
  { emoji: '🦅', english: 'Eagle', chinese: '老鹰', options: ['Bird', 'Eagle', 'Hawk'] },
  { emoji: '🦜', english: 'Parrot', chinese: '鹦鹉', options: ['Bird', 'Parrot', 'Duck'] },
  { emoji: '🦩', english: 'Flamingo', chinese: '火烈鸟', options: ['Bird', 'Flamingo', 'Stork'] },
  { emoji: '🦚', english: 'Peacock', chinese: '孔雀', options: ['Bird', 'Peacock', 'Chicken'] },
  { emoji: '🐧', english: 'Penguin', chinese: '企鹅', options: ['Penguin', 'Bird', 'Duck'] },
  { emoji: '🦇', english: 'Bat', chinese: '蝙蝠', options: ['Bird', 'Bat', 'Mouse'] },
  { emoji: '🐝', english: 'Bee', chinese: '蜜蜂', options: ['Bee', 'Fly', 'Ant'] },
  { emoji: '🐛', english: 'Bug', chinese: '虫子', options: ['Bug', 'Ant', 'Bee'] },
  { emoji: '🦋', english: 'Butterfly', chinese: '蝴蝶', options: ['Butterfly', 'Bee', 'Bird'] },
  { emoji: '🐌', english: 'Snail', chinese: '蜗牛', options: ['Snail', 'Bug', 'Worm'] },
  { emoji: '🐞', english: 'Ladybug', chinese: '瓢虫', options: ['Ladybug', 'Bee', 'Ant'] },
  { emoji: '🐜', english: 'Ant', chinese: '蚂蚁', options: ['Ant', 'Bee', 'Bug'] },
  { emoji: '🦟', english: 'Mosquito', chinese: '蚊子', options: ['Mosquito', 'Fly', 'Bee'] },
  { emoji: '🦗', english: 'Cricket', chinese: '蟋蟀', options: ['Cricket', 'Bug', 'Frog'] },
  { emoji: '🐭', english: 'Mouse', chinese: '老鼠', options: ['Mouse', 'Rat', 'Hamster'] },
  { emoji: '🐹', english: 'Hamster', chinese: '仓鼠', options: ['Hamster', 'Mouse', 'Rabbit'] },
  { emoji: '🐿️', english: 'Squirrel', chinese: '松鼠', options: ['Squirrel', 'Mouse', 'Rabbit'] },
  { emoji: '🦔', english: 'Hedgehog', chinese: '刺猬', options: ['Hedgehog', 'Mouse', 'Porcupine'] },
  { emoji: '🦊', english: 'Fox', chinese: '狐狸', options: ['Fox', 'Wolf', 'Dog'] },
  { emoji: '🐺', english: 'Wolf', chinese: '狼', options: ['Wolf', 'Fox', 'Dog'] },
  { emoji: '🦝', english: 'Raccoon', chinese: '浣熊', options: ['Raccoon', 'Fox', 'Bear'] },
  { emoji: '🐗', english: 'Boar', chinese: '野猪', options: ['Boar', 'Pig', 'Bear'] },
  { emoji: '🦌', english: 'Deer', chinese: '鹿', options: ['Deer', 'Horse', 'Cow'] },
  { emoji: '🐪', english: 'Camel', chinese: '骆驼', options: ['Camel', 'Horse', 'Donkey'] },
  { emoji: '🦒', english: 'Giraffe', chinese: '长颈鹿', options: ['Giraffe', 'Horse', 'Deer'] },
  { emoji: '🐃', english: 'Buffalo', chinese: '水牛', options: ['Buffalo', 'Cow', 'Ox'] },
  { emoji: '🦏', english: 'Rhinoceros', chinese: '犀牛', options: ['Rhinoceros', 'Hippo', 'Elephant'] },
  { emoji: '🦛', english: 'Hippopotamus', chinese: '河马', options: ['Hippopotamus', 'Rhinoceros', 'Elephant'] },
  { emoji: '🐆', english: 'Leopard', chinese: '豹子', options: ['Leopard', 'Cheetah', 'Tiger'] },
  { emoji: '🐅', english: 'Tiger', chinese: '老虎', options: ['Tiger', 'Lion', 'Leopard'] },
  { emoji: '🦍', english: 'Gorilla', chinese: '大猩猩', options: ['Gorilla', 'Monkey', 'Ape'] },
  { emoji: '🐒', english: 'Ape', chinese: '猿', options: ['Monkey', 'Ape', 'Gorilla'] },
  { emoji: '🦧', english: 'Orangutan', chinese: '猩猩', options: ['Orangutan', 'Monkey', 'Ape'] },
  { emoji: '🐩', english: 'Poodle', chinese: '贵宾犬', options: ['Poodle', 'Dog', 'Puppy'] },
  { emoji: '🐕', english: 'Puppy', chinese: '小狗', options: ['Puppy', 'Dog', 'Kitten'] },
  { emoji: '🐈', english: 'Kitten', chinese: '小猫', options: ['Kitten', 'Cat', 'Puppy'] },
  { emoji: '🦮', english: 'Guide Dog', chinese: '导盲犬', options: ['Guide Dog', 'Dog', 'Puppy'] },
  { emoji: '🐕‍🦺', english: 'Service Dog', chinese: '服务犬', options: ['Service Dog', 'Dog', 'Guide Dog'] },
  { emoji: '🦙', english: 'Llama', chinese: '羊驼', options: ['Llama', 'Camel', 'Sheep'] },
  { emoji: '🦘', english: 'Kangaroo', chinese: '袋鼠', options: ['Kangaroo', 'Rabbit', 'Deer'] },
  { emoji: '🦡', english: 'Badger', chinese: '獾', options: ['Badger', 'Bear', 'Raccoon'] },
  { emoji: '🦨', english: 'Skunk', chinese: '臭鼬', options: ['Skunk', 'Badger', 'Raccoon'] },
  { emoji: '🦫', english: 'Beaver', chinese: '海狸', options: ['Beaver', 'Otter', 'Muskrat'] },
  { emoji: '🦦', english: 'Otter', chinese: '水獭', options: ['Otter', 'Beaver', 'Seal'] },
  { emoji: '🦭', english: 'Seal', chinese: '海豹', options: ['Seal', 'Otter', 'Walrus'] },
  { emoji: '🦆', english: 'Goose', chinese: '鹅', options: ['Goose', 'Duck', 'Swan'] },
  { emoji: '🦢', english: 'Swan', chinese: '天鹅', options: ['Swan', 'Duck', 'Goose'] },
  { emoji: '🦃', english: 'Turkey', chinese: '火鸡', options: ['Turkey', 'Chicken', 'Peacock'] },
  { emoji: '🐓', english: 'Rooster', chinese: '公鸡', options: ['Rooster', 'Chicken', 'Hen'] },
  { emoji: '🐣', english: 'Chick', chinese: '小鸡', options: ['Chick', 'Chicken', 'Duckling'] },
  { emoji: '🐤', english: 'Duckling', chinese: '小鸭', options: ['Duckling', 'Chick', 'Duck'] },
  { emoji: '🐦‍⬛', english: 'Crow', chinese: '乌鸦', options: ['Crow', 'Bird', 'Raven'] },
  { emoji: '🕊️', english: 'Dove', chinese: '鸽子', options: ['Dove', 'Bird', 'Pigeon'] },
  { emoji: '🦅', english: 'Hawk', chinese: '鹰', options: ['Hawk', 'Eagle', 'Falcon'] },
  { emoji: '🦉', english: 'Barn Owl', chinese: '仓鸮', options: ['Barn Owl', 'Owl', 'Bird'] },
  { emoji: '🐸', english: 'Toad', chinese: '蟾蜍', options: ['Toad', 'Frog', 'Salamander'] },
  { emoji: '🦎', english: 'Gecko', chinese: '壁虎', options: ['Gecko', 'Lizard', 'Salamander'] },
  { emoji: '🐍', english: 'Python', chinese: '蟒蛇', options: ['Python', 'Snake', 'Boa'] },
  { emoji: '🐢', english: 'Tortoise', chinese: '陆龟', options: ['Tortoise', 'Turtle', 'Snail'] },
  { emoji: '🦕', english: 'Brachiosaurus', chinese: '腕龙', options: ['Brachiosaurus', 'Dinosaur', 'Diplodocus'] },
  { emoji: '🦖', english: 'T-Rex', chinese: '霸王龙', options: ['T-Rex', 'Dinosaur', 'Velociraptor'] },
  { emoji: '🐉', english: 'Dragon', chinese: '龙', options: ['Dragon', 'Dinosaur', 'Lizard'] },
  { emoji: '🦋', english: 'Moth', chinese: '飞蛾', options: ['Moth', 'Butterfly', 'Bee'] },
  { emoji: '🐛', english: 'Caterpillar', chinese: '毛毛虫', options: ['Caterpillar', 'Bug', 'Worm'] },
  { emoji: '🪱', english: 'Worm', chinese: '蚯蚓', options: ['Worm', 'Snake', 'Bug'] },
  { emoji: '🐜', english: 'Termite', chinese: '白蚁', options: ['Termite', 'Ant', 'Bug'] },
  { emoji: '🪲', english: 'Beetle', chinese: '甲虫', options: ['Beetle', 'Bug', 'Ladybug'] },
  { emoji: '🪳', english: 'Cockroach', chinese: '蟑螂', options: ['Cockroach', 'Bug', 'Beetle'] },
  { emoji: '🦂', english: 'Scorpion', chinese: '蝎子', options: ['Scorpion', 'Spider', 'Crab'] },
  { emoji: '🕷️', english: 'Spider', chinese: '蜘蛛', options: ['Spider', 'Scorpion', 'Ant'] },
  { emoji: '🕸️', english: 'Web', chinese: '蛛网', options: ['Web', 'Spider', 'Cocoon'] },
  { emoji: '🐚', english: 'Shell', chinese: '贝壳', options: ['Shell', 'Snail', 'Crab'] },
  { emoji: '🐠', english: 'Tropical Fish', chinese: '热带鱼', options: ['Tropical Fish', 'Fish', 'Goldfish'] },
  { emoji: '🐡', english: 'Pufferfish', chinese: '河豚', options: ['Pufferfish', 'Fish', 'Blowfish'] },
  { emoji: '🐋', english: 'Blue Whale', chinese: '蓝鲸', options: ['Blue Whale', 'Whale', 'Fish'] },
  { emoji: '🦭', english: 'Walrus', chinese: '海象', options: ['Walrus', 'Seal', 'Sea Lion'] },
  { emoji: '🐬', english: 'Porpoise', chinese: '鼠海豚', options: ['Porpoise', 'Dolphin', 'Whale'] },
  { emoji: '🦈', english: 'Hammerhead', chinese: '锤头鲨', options: ['Hammerhead', 'Shark', 'Fish'] },
  { emoji: '🐟', english: 'Salmon', chinese: '三文鱼', options: ['Salmon', 'Fish', 'Trout'] },
  { emoji: '🐟', english: 'Goldfish', chinese: '金鱼', options: ['Goldfish', 'Fish', 'Koi'] },
  { emoji: '🦐', english: 'Lobster', chinese: '龙虾', options: ['Lobster', 'Shrimp', 'Crab'] },
  { emoji: '🦞', english: 'Crayfish', chinese: '小龙虾', options: ['Crayfish', 'Lobster', 'Shrimp'] },
  { emoji: '🦑', english: 'Squid', chinese: '鱿鱼', options: ['Squid', 'Octopus', 'Cuttlefish'] },
  { emoji: '🐙', english: 'Cuttlefish', chinese: '墨鱼', options: ['Cuttlefish', 'Octopus', 'Squid'] },
  { emoji: '🪸', english: 'Coral', chinese: '珊瑚', options: ['Coral', 'Shell', 'Anemone'] },
  { emoji: '🐌', english: 'Slug', chinese: '蛞蝓', options: ['Slug', 'Snail', 'Worm'] },
  { emoji: '🦠', english: 'Amoeba', chinese: '变形虫', options: ['Amoeba', 'Bug', 'Germ'] },
  { emoji: '🦮', english: 'Sheepdog', chinese: '牧羊犬', options: ['Sheepdog', 'Dog', 'Wolf'] },
  { emoji: '🐕', english: 'Husky', chinese: '哈士奇', options: ['Husky', 'Dog', 'Wolf'] },
  { emoji: '🐩', english: 'Pomeranian', chinese: '博美', options: ['Pomeranian', 'Dog', 'Poodle'] },
  { emoji: '🐈', english: 'Persian Cat', chinese: '波斯猫', options: ['Persian Cat', 'Cat', 'Kitten'] },
  { emoji: '🐇', english: 'Bunny', chinese: '小兔', options: ['Bunny', 'Rabbit', 'Hare'] },
  { emoji: '🦌', english: 'Moose', chinese: '驼鹿', options: ['Moose', 'Deer', 'Elk'] },
  { emoji: '🐐', english: 'Goat', chinese: '山羊', options: ['Goat', 'Sheep', 'Ram'] },
  { emoji: '🐏', english: 'Ram', chinese: '公羊', options: ['Ram', 'Sheep', 'Goat'] },
  { emoji: '🐑', english: 'Lamb', chinese: '小羊', options: ['Lamb', 'Sheep', 'Goat'] },
  { emoji: '🐖', english: 'Sow', chinese: '母猪', options: ['Sow', 'Pig', 'Boar'] },
  { emoji: '🐎', english: 'Pony', chinese: '小马', options: ['Pony', 'Horse', 'Donkey'] },
  { emoji: '🫏', english: 'Donkey', chinese: '驴', options: ['Donkey', 'Horse', 'Mule'] },
  { emoji: '🐫', english: 'Dromedary', chinese: '单峰驼', options: ['Dromedary', 'Camel', 'Llama'] },
  { emoji: '🦣', english: 'Mammoth', chinese: '猛犸象', options: ['Mammoth', 'Elephant', 'Walrus'] },
  { emoji: '🦜', english: 'Macaw', chinese: '金刚鹦鹉', options: ['Macaw', 'Parrot', 'Bird'] },
  { emoji: '🦩', english: 'Stork', chinese: '鹳', options: ['Stork', 'Flamingo', 'Crane'] },
  { emoji: '🐦', english: 'Hummingbird', chinese: '蜂鸟', options: ['Hummingbird', 'Bird', 'Bee'] },
  { emoji: '🦤', english: 'Dodo', chinese: '渡渡鸟', options: ['Dodo', 'Bird', 'Ostrich'] },
  { emoji: '🦩', english: 'Crane', chinese: '鹤', options: ['Crane', 'Stork', 'Flamingo'] },
  { emoji: '🦅', english: 'Falcon', chinese: '猎鹰', options: ['Falcon', 'Hawk', 'Eagle'] },
  { emoji: '🐦‍⬛', english: 'Raven', chinese: '渡鸦', options: ['Raven', 'Crow', 'Bird'] },
  { emoji: '🐧', english: 'King Penguin', chinese: '王企鹅', options: ['King Penguin', 'Penguin', 'Bird'] },
  { emoji: '🦉', english: 'Screech Owl', chinese: '鸣角鸮', options: ['Screech Owl', 'Owl', 'Bird'] },
  { emoji: '🦎', english: 'Chameleon', chinese: '变色龙', options: ['Chameleon', 'Lizard', 'Gecko'] },
  { emoji: '🐍', english: 'Cobra', chinese: '眼镜蛇', options: ['Cobra', 'Snake', 'Python'] },
  { emoji: '🐢', english: 'Sea Turtle', chinese: '海龟', options: ['Sea Turtle', 'Turtle', 'Tortoise'] },
  { emoji: '🐸', english: 'Tree Frog', chinese: '树蛙', options: ['Tree Frog', 'Frog', 'Toad'] },
  { emoji: '🦋', english: 'Monarch', chinese: '帝王蝶', options: ['Monarch', 'Butterfly', 'Moth'] },
]

export const fruitQuestions = [
  { emoji: '🍎', english: 'Apple', chinese: '苹果', options: ['Apple', 'Orange', 'Pear'] },
  { emoji: '🍌', english: 'Banana', chinese: '香蕉', options: ['Grape', 'Banana', 'Apple'] },
  { emoji: '🍊', english: 'Orange', chinese: '橙子', options: ['Orange', 'Lemon', 'Peach'] },
  { emoji: '🍇', english: 'Grape', chinese: '葡萄', options: ['Kiwi', 'Grape', 'Cherry'] },
  { emoji: '🍉', english: 'Watermelon', chinese: '西瓜', options: ['Watermelon', 'Apple', 'Banana'] },
  { emoji: '🍓', english: 'Strawberry', chinese: '草莓', options: ['Cherry', 'Strawberry', 'Grape'] },
  { emoji: '🍐', english: 'Pear', chinese: '梨', options: ['Apple', 'Pear', 'Mango'] },
  { emoji: '🍑', english: 'Peach', chinese: '桃子', options: ['Peach', 'Orange', 'Banana'] },
  { emoji: '🍒', english: 'Cherry', chinese: '樱桃', options: ['Grape', 'Cherry', 'Strawberry'] },
  { emoji: '🍋', english: 'Lemon', chinese: '柠檬', options: ['Lemon', 'Orange', 'Apple'] },
  { emoji: '🥭', english: 'Mango', chinese: '芒果', options: ['Banana', 'Mango', 'Pear'] },
  { emoji: '🥝', english: 'Kiwi', chinese: '猕猴桃', options: ['Kiwi', 'Grape', 'Lemon'] },
]

export const vehicleQuestions = [
  { emoji: '🚗', english: 'Car', chinese: '小汽车', options: ['Bus', 'Car', 'Bike'] },
  { emoji: '🚌', english: 'Bus', chinese: '公共汽车', options: ['Bus', 'Train', 'Car'] },
  { emoji: '🚲', english: 'Bike', chinese: '自行车', options: ['Car', 'Bike', 'Boat'] },
  { emoji: '✈️', english: 'Plane', chinese: '飞机', options: ['Helicopter', 'Plane', 'Train'] },
  { emoji: '🚂', english: 'Train', chinese: '火车', options: ['Train', 'Bus', 'Taxi'] },
  { emoji: '⛵', english: 'Boat', chinese: '小船', options: ['Ship', 'Boat', 'Car'] },
  { emoji: '🚚', english: 'Truck', chinese: '卡车', options: ['Truck', 'Bus', 'Car'] },
  { emoji: '🚁', english: 'Helicopter', chinese: '直升机', options: ['Plane', 'Helicopter', 'Boat'] },
  { emoji: '🚕', english: 'Taxi', chinese: '出租车', options: ['Bus', 'Taxi', 'Truck'] },
  { emoji: '🚀', english: 'Rocket', chinese: '火箭', options: ['Rocket', 'Plane', 'Train'] },
]

export const bodyQuestions = [
  { emoji: '👤', english: 'Head', chinese: '头', options: ['Head', 'Hand', 'Foot'] },
  { emoji: '👁️', english: 'Eye', chinese: '眼睛', options: ['Ear', 'Eye', 'Nose'] },
  { emoji: '👃', english: 'Nose', chinese: '鼻子', options: ['Mouth', 'Nose', 'Eye'] },
  { emoji: '👄', english: 'Mouth', chinese: '嘴巴', options: ['Mouth', 'Head', 'Ear'] },
  { emoji: '👂', english: 'Ear', chinese: '耳朵', options: ['Eye', 'Ear', 'Finger'] },
  { emoji: '✋', english: 'Hand', chinese: '手', options: ['Foot', 'Hand', 'Arm'] },
  { emoji: '🦶', english: 'Foot', chinese: '脚', options: ['Foot', 'Hand', 'Leg'] },
  { emoji: '💪', english: 'Arm', chinese: '手臂', options: ['Arm', 'Leg', 'Hand'] },
  { emoji: '🦵', english: 'Leg', chinese: '腿', options: ['Arm', 'Leg', 'Foot'] },
  { emoji: '☝️', english: 'Finger', chinese: '手指', options: ['Finger', 'Hand', 'Foot'] },
]

export const colorQuestions = [
  { color: '#FF4757', english: 'Red', chinese: '红色' },
  { color: '#2ED573', english: 'Green', chinese: '绿色' },
  { color: '#1E90FF', english: 'Blue', chinese: '蓝色' },
  { color: '#FFA502', english: 'Orange', chinese: '橙色' },
  { color: '#FFD93D', english: 'Yellow', chinese: '黄色' },
  { color: '#A78BFA', english: 'Purple', chinese: '紫色' },
  { color: '#FF6B9D', english: 'Pink', chinese: '粉色' },
  { color: '#2C3E50', english: 'Black', chinese: '黑色' },
  { color: '#FFFFFF', english: 'White', chinese: '白色' },
  { color: '#8B4513', english: 'Brown', chinese: '棕色' },
  { color: '#95A5A6', english: 'Gray', chinese: '灰色' },
  { color: '#FFD700', english: 'Gold', chinese: '金色' },
]

export const comparePairs = [
  { big: '🐘', bigL: '大象', small: '🐭', smallL: '老鼠' },
  { big: '🚗', bigL: '汽车', small: '🚲', smallL: '自行车' },
  { big: '🏠', bigL: '房子', small: '⛺', smallL: '帐篷' },
  { big: '🌳', bigL: '大树', small: '🌷', smallL: '小花' },
  { big: '🐋', bigL: '鲸鱼', small: '🐟', smallL: '小鱼' },
  { big: '🦒', bigL: '长颈鹿', small: '🐰', smallL: '兔子' },
  { big: '🌞', bigL: '太阳', small: '🌙', smallL: '月亮' },
  { big: '🏔️', bigL: '大山', small: '🪨', smallL: '石头' },
  { big: '🦅', bigL: '老鹰', small: '🐦', smallL: '小鸟' },
  { big: '🐉', bigL: '恐龙', small: '🦎', smallL: '蜥蜴' },
  { big: '🍉', bigL: '西瓜', small: '🍇', smallL: '葡萄' },
  { big: '🌊', bigL: '大海', small: '💧', smallL: '水滴' },
]
